### ISSUE TITLE
Etcd v3 cluster how to use it?

### ISSUE THREAD

**Issue by XMAN-WOMBAT** [etcd-cpp-apiv3/etcd-cpp-apiv3#1]
hello!
          etcd v3 cluster how to use it? Can config  etcd::Client etcd("http://192.1.1.1:2379,http://192.1.1.2:2379,http://192.1.1.3:2379") ?

**Comment by mauiarches** [comment]
Hi,

Unfortunately specifying multiple end-points is not yet supported.

**Comment by sarat-k** [comment]
Hi XMAN,

Were you able to use this library ? I compiled it and linked the resultant library to my app library (which is .so by itself). When I load the main app that links to my app library (which in turn uses this library) I get the following error:

undefined symbol: _ZTVN12etcdserverpb5Watch4StubE

Regards,
SK

**Comment by sighingnow** [comment]
After #16 fixes the feature (multiple end-points support) should work as:

```cpp
etcd::Client etcd("http://192.1.1.1:2379,http://192.1.1.2:2379,http://192.1.1.3:2379")
```

The gRPC's load balancer is used behind the screen.

**Comment by sighingnow** [comment]
For the "undefined symbol: _ZTVN12etcdserverpb5Watch4StubE" issue, more detail information is needed to get it fixed.

Feel free to reopen.
