### ISSUE TITLE
invalid auth token error

### ISSUE THREAD

**Issue by wangyi1310** [etcd-cpp-apiv3/etcd-cpp-apiv3#107]
Use password authentication, but the token expires after 5 minutes

error msg: etcd get err:16,msg:etcdserver: invalid auth token

**Comment by sighingnow** [comment]
Will be fixed by checking and renewing the token every time we use it.

For a workaround, you could specify the `auth-token-ttl` option with a longer value when launching etcd.

**Comment by sighingnow** [comment]
A custom `auth_token_ttl` parameter has been added in #109 to auto refresh the token before it been expired.
