### ISSUE TITLE
[BUG] In function `etcd::Client::observe` parameter `callback` not be used

### ISSUE THREAD

**Issue by zxq-bit** [etcd-cpp-apiv3/etcd-cpp-apiv3#108]
When I try to use observe to watch changes of election, I found the callback function not be executed. Then I read the implement of [etcd::Client::observe](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/src/Client.cpp#L959), found this parameter not be used.

I'm using version in tag [0.2.2](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/releases/tag/v0.2.2). But the newest version in master branch has the same problem, too.

**Comment by sighingnow** [comment]
Should be a bug.

**Comment by sighingnow** [comment]
Fixed on master branch, where a new API that does accept a callback was added.
