### ISSUE TITLE
etcd-cpp-apiv3 building debian package from source

### ISSUE THREAD

**Issue by sighingnow** [etcd-cpp-apiv3/etcd-cpp-apiv3#110]
> I am trying to build debian package from source with newer protobuf version:
>
> I tried the following commands in ubuntu:
>
> mkdir build
> cd build
> cmake ..
> cpack
>
> that seems to create the file  etcd-cpp-api-0.2.2-Linux.tar.gz

From Alex Hurd

**Comment by hurdad** [comment]
thanks for posting

**Comment by sighingnow** [comment]
I would like to know what your problem exactly is. Are you facing with some build errors? Or, are you not sure how to build such a deb package?

**Comment by hurdad** [comment]
I am not sure how to build debian package with cmake/cpack

**Comment by sighingnow** [comment]
> I am not sure how to build debian package with cmake/cpack

You could simply

```
mkdir build
cd build
cmake ..
cpack -G DEB
```

which will generate the deb package that you want.

I have add a github action to verfify that: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-deb-package.yml
