### ISSUE TITLE
Can be lease ttl associated to a lock be renewed/extended?

### ISSUE THREAD

**Issue by dpastorc** [etcd-cpp-apiv3/etcd-cpp-apiv3#113]
Hello,

I'm new using etcd-cpp-apiv3, and I have a situation where I want to renew the lease TTL of an already created object. There is a way to renew/extend lease ttl of a lease object acquired from `leasekeepalive(ttl_time).get()` call?
```
//...
int ttl = 60;
auto keepalive = etcd.leasekeepalive(ttl).get();
auto response = etcd.lock_with_lease(key, keepalive.Lease()).get();
if (response.is_ok()) {
  this_thread::sleep_fo(std::chrono::seconds(10));
  // At this point I would like to renew the lease ttl (e.g: to 120 seconds
  // or whatever value) to extend the amount of time that I will be the 
  // owner of the lock.
}
```
Thanks for help!

**Comment by sighingnow** [comment]
You don't need the renew the lease and the `keepalive` object will handle that.

A `KeepAlive` object has a background thread that will guarantee the lease been renewed/extended before expired.
