### ISSUE TITLE
Unlock doesn't revoke associated lease

### ISSUE THREAD

**Issue by dpastorc** [etcd-cpp-apiv3/etcd-cpp-apiv3#116]
Hello,

I have found that when you call `unlock()` over a lock created using  `lock(std::string const &key, int lease_ttl)` (without provide external keepalive/lease-id), the unlock operation removes the lock from server and it deletes the KeepAlive object created internally as expected, but it doesn't revoke the lease associated to that lock, so the lease continue alive in server side up to it will expire. Should that lease also be revoked as part of  `unlock()` operation?

Apart of that, it could be interesting to return the lease_id generated by the library associated to the lock to be able to track the remain ttl of the lease from outside.

Thanks.

**Comment by sighingnow** [comment]
> Apart of that, it could be interesting to return the lease_id generated by the library associated to the lock to be able to track the remain ttl of the lease from outside.

Yes, adding a release action would be better. I will improve that.

**Comment by sighingnow** [comment]
> > Apart of that, it could be interesting to return the lease_id generated by the library associated to the lock to be able to track the remain ttl of the lease from outside.
> 
> Yes, adding a release action would be better. I will improve that.

Fixed in #130.
