### ISSUE TITLE
need more requirements about library's version

### ISSUE THREAD

**Issue by CoderSong2015** [etcd-cpp-apiv3/etcd-cpp-apiv3#119]
especially about the version of boost、protobuf..

**Comment by sighingnow** [comment]
Actually I haven't test the min/max supported dependency version yet, but do have tested against common distributions (Ubuntu 18.04, Ubuntu 20.04, Mac).

**Comment by CoderSong2015** [comment]
what about centos?   I'm trying to build every from source on centos...

**Comment by sighingnow** [comment]
> what about centos? I'm trying to build every from source on centos...

I could add a CI on centos 7/8.

**Comment by sighingnow** [comment]
Please refer to https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/centos-latest.yml for how to build & run examples on CentOS.
