### ISSUE TITLE
The pplx thread pool still exists after the etcd client destructed

### ISSUE THREAD

**Issue by chijinxina** [etcd-cpp-apiv3/etcd-cpp-apiv3#12]
I would to know how to kill the pplx thread after the etcd client destrutor.

**Comment by sighingnow** [comment]
AFAIK, this cannot be implemented, since pplx use a singleton shared thread pool to submit tasks. If we destroy that singleton, we cannot continue to submit any pplx tasks any more.

**Comment by sighingnow** [comment]
A separated target `etcd-cpp-api-core` library has been added in #130 which doesn't link aganist the pplx library (thus no such thread pool).

Users are free to choose their own thread model based on the synchronous API exposed in `SyncClient` (in `etcd-cpp-api-core` target).

Closing this issue as fixed.
