### ISSUE TITLE
watcher parameter bug

### ISSUE THREAD

**Issue by FAKERINHEART** [etcd-cpp-apiv3/etcd-cpp-apiv3#125]
parameter `fromIndex` should be int64

**Comment by FAKERINHEART** [comment]
could you tell when next `release version` will be bumped?

**Comment by sighingnow** [comment]
> could you tell when next `release version` will be bumped? @sighingnow

Bumpped to v0.2.5.

**Comment by sighingnow** [comment]
> > > could you tell when next `release version` will be bumped? @sighingnow
> > 
> > 
> > Bumpped to v0.2.5.
> 
> please release v0.2.5 as soon as possbile @sighingnow hahaha

I do have push the v0.2.5 tag.
