### ISSUE TITLE
Create ETCD Client with auth

### ISSUE THREAD

**Issue by tanviash** [etcd-cpp-apiv3/etcd-cpp-apiv3#13]
Is there a way to connect to etcd server providing auth details like username and password?

**Comment by benstadin** [comment]
+1. Certificate based auth will be relevant for me as well.

Great to see this library is revived!

**Comment by sighingnow** [comment]
The username+password based authentication has been implemented in #20. From https://etcd.io/docs/v3.4.0/learning/design-auth-v3/ I think it should be enough for etcd v3 auth.

Hi @benstadin could you proivide me further reference or documentation about certificate-based auth in etcd v3?

**Comment by sighingnow** [comment]
> +1. Certificate based auth will be relevant for me as well.
> 
> Great to see this library is revived!

Hi @benstadin certificate based auth has been added in https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/pull/42.
