### ISSUE TITLE
Segmentation fault when KeepAlive destruct

### ISSUE THREAD

**Issue by LiChengZiMu** [etcd-cpp-apiv3/etcd-cpp-apiv3#137]

**Comment by LiChengZiMu** [comment]
![wecom-temp-859e2297b37e6acc3bf45209d8577913](https://user-images.githubusercontent.com/104759475/171317354-39760db9-6248-4659-8813-2df9b45f33e4.png)

**Comment by sighingnow** [comment]
Closing as staled and we have done some enhancement over the `KeepAlive` implementation.

Feel free to reopen if you still meet the same segmentation fault on the latest master version.
