### ISSUE TITLE
请问有没有详细的API接口文档呀

### ISSUE THREAD

**Issue by pengmhm** [etcd-cpp-apiv3/etcd-cpp-apiv3#138]
请问有没有详细的API接口文档呀

**Comment by sighingnow** [comment]
Please refer to the README.md, and https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/etcd/Client.hpp.

**Comment by pengmhm** [comment]
里面没有详细的接口参数说明

**Comment by sighingnow** [comment]
> https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/etcd/Client.hpp

头文件里面的docstring都有呀。是对哪一个API的定义感觉不太清晰呀，我可以补充一下。

抱歉没有及时看到前面的comment ...

**Comment by sighingnow** [comment]
Addressed by https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/commit/92efa7c9ded9dddd07982a29350655f4ae04d876
