### ISSUE TITLE
使用带密钥访问的client会出现coredump

### ISSUE THREAD

**Issue by yess1987** [etcd-cpp-apiv3/etcd-cpp-apiv3#141]
使用k8s中的自动生成的etcd秘钥文件会出现coredump

etcd::Client etcd(str_url, "/etc/kubernetes/pki/etcd/ca.crt", "/etc/kubernetes/pki/etcd/server.crt", "/etc/kubernetes/pki/etcd/server.key", "etcd", "round_robin");

**Comment by sighingnow** [comment]
I will take it a try. Could you please provide some information about your kubernetes and etcd version?

Thanks for the reporting.

**Comment by yess1987** [comment]
环境：k8s 1.23 、etcd v3.5.3、centos Stream
问题：使用etcd-cpp-apiv3是否可以访问k8s部署的etcd（带密钥访问），是否需要的证书就是k8s给etcd生成的证书，或者哪里配置不对；标准的访问k8s环境的自带的etcd用法能否提供下样例

**Comment by sighingnow** [comment]
Fail to reproduce with the kubeadm's etcd installation:

```cpp
static std::string ca = "/etc/kubernetes/pki/etcd/ca.crt";
static std::string cert = "/etc/kubernetes/pki/etcd/server.crt";
static std::string key = "/etc/kubernetes/pki/etcd/server.key";

etcd::Client *etcd = etcd::Client::WithSSL("https://127.0.0.1:2379", ca, cert, key);

auto resp = etcd->head().get();
std::cout << resp.is_ok() << std::endl;
std::cout << resp.error_message() << std::endl;
std::cout << resp.index() << std::endl;
```

**Please make sure**:

- You have the read permission on the SSL certificates files
- Note that I didn't pass the `target_name_override` argument (in your case the "etcd" parameter) in the constructor. You could pass an empty string and take a try.

**Comment by sighingnow** [comment]
Closing. Free to reopen if you still failed to connect to the kubernetes's etcd with SSL certificates.

**Comment by BHJ1** [comment]
现象
![Image](https://github.com/user-attachments/assets/5149d0f4-7820-494a-878b-29542f283ab9)

**Comment by BHJ1** [comment]
原因
![Image](https://github.com/user-attachments/assets/1b22d238-a97d-42e6-8833-f520929eb681)
如果grpc使用了自己的boringssl,而etcd-cpp-api使用系统的openssl会出现这个问题

**Comment by BHJ1** [comment]
解决方法 
grpc编译时 cmake -DgRPC_SSL_PROVIDER=package 能够解决这种情况下出现的coredump
