### ISSUE TITLE
coredum when start the demo

### ISSUE THREAD

**Issue by xjj210130** [etcd-cpp-apiv3/etcd-cpp-apiv3#142]
0x00007fc64f0bc535 in __GI_abort () at abort.c:79
#2  0x00007fc64f484983 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fc64f48a8c6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fc64f48a901 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fc64f48ab34 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fc651fe7386 in google::protobuf::internal::LogMessage::Finish() () from /opensource/etcd/lib/libetcd-cpp-api.so
#7  0x00007fc651fe73c2 in google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&) () from /opensource/etcd/lib/libetcd-cpp-api.so
#8  0x00007fc651fa8e39 in google::protobuf::internal::(anonymous namespace)::Register(google::protobuf::MessageLite const*, int, google::protobuf::internal::ExtensionInfo) () from /opensource/etcd/lib/libetcd-cpp-api.so
#9  0x00007fc651fa917b in google::protobuf::internal::ExtensionSet::RegisterExtension(google::protobuf::MessageLite const*, int, unsigned char, bool, bool) () from /opensource/etcd/lib/libetcd-cpp-api.so
#10 0x00007fc651ddcac2 in google::protobuf::internal::PrimitiveTypeTraits<bool>::Register<google::protobuf::EnumOptions> (number=62001, type=8 '\b', is_packed=false) at /usr/local/include/google/protobuf/extension_set.h:952
#11 0x00007fc651ddc9b6 in google::protobuf::internal::ExtensionIdentifier<google::protobuf::EnumOptions, google::protobuf::internal::PrimitiveTypeTraits<bool>, (unsigned char)8, false>::Register (number=62001) at /usr/local/include/google/protobuf/extension_set.h:1366
#12 0x00007fc651ddc850 in google::protobuf::internal::ExtensionIdentifier<google::protobuf::EnumOptions, google::protobuf::internal::PrimitiveTypeTraits<bool>, (unsigned char)8, false>::ExtensionIdentifier (this=0x7fc6527c8600 <gogoproto::goproto_enum_prefix>, number=62001, default_value=false) at /usr/local/include/google/protobuf/extension_set.h:1358
#13 0x00007fc651ddbce7 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /opensource/etcd-cpp-apiv3/build/proto/gen/proto/gogoproto/gogo.pb.cc:159
#14 0x00007fc651ddc81c in _GLOBAL__sub_I_gogo.pb.cc(void) () at /opensource/etcd-cpp-apiv3/build/proto/gen/proto/gogoproto/gogo.pb.cc:398
#15 0x00007fc6527ef37a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffb9edf0c8, env=env@entry=0x7fffb9edf0d8) at dl-init.c:72
#16 0x00007fc6527ef476 in call_init (env=0x7fffb9edf0d8, argv=0x7fffb9edf0c8, argc=1, l=<optimized out>) at dl-init.c:30
#17 _dl_init (main_map=0x7fc652809190, argc=1, argv=0x7fffb9edf0c8, env=0x7fffb9edf0d8) at dl-init.c:119
#18 0x00007fc6527e10ca in _dl_start_user () from [/lib64/ld-linux-x86-64.so.2[]

The main function is not work the coredump happened

**Comment by yess1987** [comment]
你这个也是带密钥访问出现的吗

**Comment by xjj210130** [comment]
不是，这个是pb的static 函数导致的，我后面就不使用这个了。

**Comment by sighingnow** [comment]
这个start the demo，有可以reproduce得code么？

**Comment by sighingnow** [comment]
环境是？看起来是依赖了一个静态链接的protobuf library？

**Comment by sighingnow** [comment]
Closing as lack of information from the end user.
