### ISSUE TITLE
使用c封装c++库，父进程fork 子进程时，子进程会出现死锁状态

### ISSUE THREAD

**Issue by yess1987** [etcd-cpp-apiv3/etcd-cpp-apiv3#147]
```cpp
if( (pid = fork()) < 0 )
    {
            printf("\n");
            printf("fork() error: %s\n",strerror(errno));
            return -2;
    }
    else if(0 == pid)
    {
            printf("\n");
            printf("child process PID[%d] running!!!\n",getpid());
            g_var++;
            var++;
            //test_case_set();
            test_case_get();
            printf("child process1 PID[%d] running!!!\n",getpid());
            sleep(1);
    }
    else
    {
            printf("\n");
            printf("parent process PID[%d] waiting!!!\n",getpid());
            sleep(5);
            //test_case_set();
            //test_case_get();
    }
```

Aug  3 11:32:04 HikvisionOS kernel: grpc_global_tim[51533]: segfault at 79726f ip 00007f9b308e787c sp 00007f9b29ff2138 error 4 in libc.so.6[7f9b3081b000+176000]
Aug  3 11:32:04 HikvisionOS kernel: Code: 00 00 00 00 00 66 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f8 62 a1 fd 00 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 34 01 00 00 <62> f3 7d 20 3f 07 00 c5 fb 93 c0 85 c0 74 55 f3 0f bc c0 c3 f3 0f

**Comment by sighingnow** [comment]
Will try to reproduce.

**Comment by sighingnow** [comment]
Test case added in https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/pull/196.

It does work when the parent process and the child process both hold their own client instance.
