### ISSUE TITLE
observe接口缺失

### ISSUE THREAD

**Issue by 1358035421** [etcd-cpp-apiv3/etcd-cpp-apiv3#148]
您好~
在commit : 8da89464096cc91b2b4ab8e67e02ea8b989f7a59 的重构中
看到将以下接口删除

    std::unique_ptr<Observer> observe(std::string const &name,
                                      std::function<void(Response)> callback,
                                      const bool once = false);

请问一下为什么要删除这个接口，另外由于在测试中没有observe的示例，想请教一下observe的正确使用姿势~

**Comment by sighingnow** [comment]
我印象中是因为现在的已经是够用了，我晚点double check一下，在readme里面加一个例子。

**Comment by sighingnow** [comment]
Example has been added to README in https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/commit/30c880dd05e96dcd1b145fb984be4bb98978a4f0.
