### ISSUE TITLE
ls有没有精确匹配功能

### ISSUE THREAD

**Issue by wangxuheng** [etcd-cpp-apiv3/etcd-cpp-apiv3#151]
![image](https://user-images.githubusercontent.com/34324714/184852111-26f6fef6-f96a-47e9-a39f-b551f06566d7.png)
Eg:
etcd数据库中存在key: /mod/test72chg，使用etcd.ls接口查询/mod/test72也会返回/mod/test72chg 
有没有方法查询/mod/test72这个全匹配的key是否存在？

**Comment by sighingnow** [comment]
完全匹配，而不是list 前缀，需要用 `client.get()` 。

`client.list()` 的语义是按照前缀匹配。

https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/ca2553e30dad015326b094beede06e4846bd3ad2/tst/EtcdTest.cpp#L37-L46

**Comment by wangxuheng** [comment]
明白了，多谢!
还想问下,我们还有个通过list只看下一级的节点需求，这个可以实现吗？
eg: 
数据库中存在key:  /mod/test/test1    /mod/test/test2   /mod/test/test3  /mod/test_1/1
通过etcd.ls("/mod/test")  获取到test1、test2、test3

**Comment by sighingnow** [comment]
这个没有。因为在etcd里面并不存在真实的目录结构，所有的key都只是字符串，list 什么的这些API只能按照key的前缀匹配。

**Comment by wangxuheng** [comment]
etcd V2版本是不是存在真实的目录结构？如何保持V3版本和V2版本兼容？
