### ISSUE TITLE
能否提供编译后的组件在release page中呢？ 自己准备的编译环境各种报错。

### ISSUE THREAD

**Issue by HouJiangtao** [etcd-cpp-apiv3/etcd-cpp-apiv3#152]
as the title

**Comment by sighingnow** [comment]
具体平台是？

**Comment by sighingnow** [comment]
编译环境啥错呀

**Comment by HouJiangtao** [comment]
我在ubuntu上编译的，由于虚拟机环境资源太少 编译cmake总失败，现在增加到8核 6G，已经解决了，并且 源码已正常编译通过了，谢谢！

**Comment by sighingnow** [comment]
> 我在ubuntu上编译的，由于虚拟机环境资源太少 编译cmake总失败，现在增加到8核 6G，已经解决了，并且 源码已正常编译通过了，谢谢！

好的。你`make`的时候不要加 `-j` 参数就好了应该。

**Comment by sighingnow** [comment]
> > 我在ubuntu上编译的，由于虚拟机环境资源太少 编译cmake总失败，现在增加到8核 6G，已经解决了，并且 源码已正常编译通过了，谢谢！
> 
> 好的。你`make`的时候不要加 `-j` 参数就好了应该。

我update了README里面 `make -j` 的地方，改成了 `make -j$(nproc)`.

**Comment by HouJiangtao** [comment]
好的  谢谢 另外想再问下 我在c项目里能使用这些接口吗？

**Comment by sighingnow** [comment]
> 

没有提供现成的，你需要的话得自己封装了。封装C接口的话，建议你封装同步API：https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/etcd/SyncClient.hpp

**Comment by wangxuheng** [comment]
同步API和非同步API有什么区别呢？
