### ISSUE TITLE
Modifying a value 示例代码有个笔误

### ISSUE THREAD

**Issue by hz-bin** [etcd-cpp-apiv3/etcd-cpp-apiv3#154]
https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#modifying-a-value

std::ecxeption const & ex
要改成 std::exception const & ex

**Comment by sighingnow** [comment]
@hz-bin 感谢指出，可以交个pr不 ❤️

**Comment by hz-bin** [comment]
> @hz-bin 感谢指出，可以交个pr不 ❤️

提交了，大佬看看
https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/pull/155
