### ISSUE TITLE
同步API和非同步API有什么区别呢？

### ISSUE THREAD

**Issue by wangxuheng** [etcd-cpp-apiv3/etcd-cpp-apiv3#156]

**Comment by sighingnow** [comment]
同步API会阻塞，异步API会返回一个promise。参考对比 `Client.hpp` 和 `SyncClient.hpp`.

**Comment by sighingnow** [comment]
See also: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#sync-vs-async-runtime
