### ISSUE TITLE
etcd V2版本是不是存在真实的目录结构？如何保持V3版本和V2版本兼容？

### ISSUE THREAD

**Issue by wangxuheng** [etcd-cpp-apiv3/etcd-cpp-apiv3#157]

**Comment by sighingnow** [comment]
> etcd V2版本是不是存在真实的目录结构

我不太确定。

> 如何保持V3版本和V2版本兼容？

是在API上有特别的需求么？

**Comment by wangxuheng** [comment]
[https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/151](url)
@sighingnow #
etcd-cpp-api访问v2etcd的list
![image](https://user-images.githubusercontent.com/34324714/187683566-f6a19d70-7f64-4bf1-bb9b-d7683c3f6e9c.png)

**Comment by sighingnow** [comment]
etcd API 无法支持，从应用角度，可以先list，然后再根据自己的逻辑过滤一遍结果（key 里面有多个 `/` 就从结果中忽略）。

**Comment by sighingnow** [comment]
Closing as answered. Feel free to reopen or create new issue if there's any further question.
