### ISSUE TITLE
Can `etcd-cpp-apiv3` support C++20?

### ISSUE THREAD

**Issue by zhanghan-mq** [etcd-cpp-apiv3/etcd-cpp-apiv3#159]
I'm tring to use `etcd-cpp-apiv3` as submodule in my project, which compiles through `C++20`. Firstly, my project will compile `etcd-cpp-apiv3` without installing, and then it compiles my code which use `etcd-cpp-apiv` as a library, but it appers that `etcd-cpp-apiv3` generate compile error. I found the reason below: 
in `etcd-cpp-apiv3/CMakeLists.txt`
```
   macro(use_cxx11)
  if(CMAKE_VERSION VERSION_LESS "3.1")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")
    endif()
  else()
    set(CMAKE_CXX_STANDARD 11)
  endif()
endmacro(use_cxx11)

# ensure C++11
use_cxx11() 
```
this will force `etcd-cpp-apiv3`  to use C++11.
So, can we plan to support  C++20?

**Comment by sighingnow** [comment]
You could set `CMAKE_CXX_STANDARD` to `17` in your own project.

We currently have no plan to switch the minimal requirements of the etcd-cpp-apiv3 itself to C++17.
