### ISSUE TITLE
Can `etcd-cpp-api` support STATIC library?

### ISSUE THREAD

**Issue by zhanghan-mq** [etcd-cpp-apiv3/etcd-cpp-apiv3#161]
I added `-DBUILD_SHARED_LIBS=OFF` in linux，and got a `libetcd-cpp-api.a` , but when I use it as library to get a executable. it make some errors
```
libetcd-cpp-api.a(http.pb.cc.o): in function `void google::protobuf::internal::RepeatedPtrFieldBase::Clear<google::protobuf::RepeatedPtrField<google::api::HttpRule>::TypeHandler>()':
/usr/include/google/protobuf/repeated_field.h:1780: undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)'
```
so can `etcd-cpp-api` support STATIC?

**Comment by sighingnow** [comment]
Yes. how you link against this library? If you build the final target from command line, you need to link the protobuf and grpc libraries as well.

I suggest you use this project as a cmake subdirectory.

**Comment by zhanghan-mq** [comment]
> Yes. how you link against this library? If you build the final target from command line, you need to link the protobuf and grpc libraries as well.
> 
> I suggest you use this project as a cmake subdirectory.

Thanks, I solve this error by add `find_package(Protobuf REQUIRED)` and `find_package(gRPC REQUIRED)`
```
find_package(Protobuf QUIET REQUIRED)
find_package(gRPC REQUIRED)

add_executable(etcd-client
  etcd_client.cc
)

target_link_libraries(etcd-client
  etcd-cpp-api::etcd-cpp-api
  cpprest::cpprest
  gRPC::gpr
  gRPC::grpc
  gRPC::grpc++)

```

**Comment by sighingnow** [comment]
Closing as resolved.
