### ISSUE TITLE
AddressSanitizer报错

### ISSUE THREAD

**Issue by FAKERINHEART** [etcd-cpp-apiv3/etcd-cpp-apiv3#166]
![image](https://user-images.githubusercontent.com/13352188/192842248-565e456a-418c-4dfd-bf81-6c37f5636b8d.png)

**Comment by FAKERINHEART** [comment]
0.2.7和0.2.6都有

**Comment by sighingnow** [comment]
我怎么reproduce？方便给代码不

**Comment by sighingnow** [comment]
Not an issue of this library itself.

If you need to use address sanitizer with grpc, you'll need to rebuid grpc itself with `-fsanitizer=address`.
