### ISSUE TITLE
VCPKG build error under windows

### ISSUE THREAD

**Issue by sdeastis** [etcd-cpp-apiv3/etcd-cpp-apiv3#171]
The latest release of the library doesn't compile with VCPKG on windows. 
Please make a new release with a working vcpkg/etcd-cpp-apiv3 set of configuration files since REF 1b68f9c79dede1264a0977a239e497358760b0ac is not compiling.

**Comment by sighingnow** [comment]
I have just tag a v0.2.8 release. May I know the error message in your build failure?

Thanks!

**Comment by sdeastis** [comment]
[install-x64-windows-dbg-out.log](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/files/9681663/install-x64-windows-dbg-out.log)

Here the log with all the errors. Derived from missing "#define NOMINMAX" which is not part of the tag 1b68f9c79dede1264a0977a239e497358760b0ac present in the portfile.cmake.

**Comment by sighingnow** [comment]
Will bump up the revision in the vcpkg script once I have access to my Windows laptop.
