### ISSUE TITLE
Replace vcpkg/CONTROL by vcpkg/vcpkg.json

### ISSUE THREAD

**Issue by CayOest** [etcd-cpp-apiv3/etcd-cpp-apiv3#175]
Hi, 
the vcpkg CONTROL files are deprecated and should be replaced by vcpkg.json:
`{
  "name": "etcd-cpp-apiv3",
  "version-string": "0.2.8",
  "description": "The etcd-cpp-apiv3 is a C++ API for etcd's v3 client API, i.e., ETCDCTL_API=3.",
  "homepage": "https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3",
  "dependencies": [
    "boost-asio",
    "boost-random",
    "boost-system",
    "boost-thread",
    "cpprestsdk",
    "grpc",
    "openssl",
    "protobuf"
  ]
}`

Cheers!

**Comment by sighingnow** [comment]
Resolved by #176.
