### ISSUE TITLE
`KeepAlive::Check()` doesn't work as expected

### ISSUE THREAD

**Issue by niyue** [etcd-cpp-apiv3/etcd-cpp-apiv3#180]
The `KeepAlive` has a `Check` function, and it is documented as:

> Check if the keep alive is still valid (invalid when there's an async exception). 
> Nothing will happen if valid and an exception will be rethrowed if invalid.

I have a test test like below:
```C++
etcd::Client client(etcd_url);

// create a lease with 30 seconds TTL
auto lease_keep_alive = client.leasekeepalive(30);
auto keep_alive = lease_keep_alive.get();
auto lease_id = keep_alive->Lease();

// revoke the lease before it reaches its TTL
client.leaserevoke(lease_id);
// retrieves its TTL again, and it is now -1
auto response = client.leasetimetolive(lease_id);
REQUIRE(response.get().value().ttl() == -1);

// I expect keep_alive->Check() to throw exception, but it does nothing, and the test case fails here
REQUIRE_THROWS(keep_alive->Check());
```

I thought if a lease is revoked, the corresponding keep alive this lease attached to will be `invalid`, so the `Check()` function should throw exception, but from what I observe, it is not the case. Probably my understanding here is not correct, could you please shed some light if this is a bug or an expected behavior? Thanks.

**Comment by sighingnow** [comment]
Fixed in #193.
