### ISSUE TITLE
Ubuntu18.04 在安装gRPC 1.27.x之后，无法成功cmake etcd-cpp-apiv3

### ISSUE THREAD

**Issue by WhiteBearWYL** [etcd-cpp-apiv3/etcd-cpp-apiv3#183]
user-linux@Robot2:~/ddb/etcd-cpp-apiv3/build$ cmake ..
-- Boost  found.
-- Found Boost components:
   system;thread;random
CMake Error at /usr/local/lib/cmake/grpc/gRPCConfig.cmake:16 (include):
  include could not find load file:

    /usr/local/lib/cmake/grpc/gRPCTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:116 (find_package)

CMake Error at CMakeLists.txt:119 (get_target_property):
  get_target_property() called with non-existent target
  "gRPC::grpc_cpp_plugin".

CMake Error at CMakeLists.txt:120 (get_target_property):
  get_target_property() called with non-existent target "gRPC::grpc".

-- Configuring incomplete, errors occurred!
See also "/home/user-linux/ddb/etcd-cpp-apiv3/build/CMakeFiles/CMakeOutput.log".
See also "/home/user-linux/ddb/etcd-cpp-apiv3/build/CMakeFiles/CMakeError.log".
CMake Error: Unable to open check cache file for write. /home/user-linux/ddb/etcd-cpp-apiv3/build/CMakeFiles/cmake.check_cache

**Comment by sighingnow** [comment]
build grpc是不是没有enable cpp plugin呀，建议参考 CI 里面的configuration哈：

https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-test.yml#L60

**Comment by WhiteBearWYL** [comment]
新的问题 在相同的环境下grpc按照参考CI安装成功后：
user-linux@Robot3:~/ddb/etcd-cpp-apiv3/build$ cmake ..
-- Boost  found.
-- Found Boost components:
   system;thread;random
CMake Error at /usr/local/lib/cmake/grpc/gRPCConfig.cmake:16 (include):
  include could not find load file:

    /usr/local/lib/cmake/grpc/gRPCTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:116 (find_package)


CMake Error at CMakeLists.txt:119 (get_target_property):
  get_target_property() called with non-existent target
  "gRPC::grpc_cpp_plugin".


CMake Error at CMakeLists.txt:120 (get_target_property):
  get_target_property() called with non-existent target "gRPC::grpc".


-- Configuring incomplete, errors occurred!
See also "/home/user-linux/ddb/etcd-cpp-apiv3/build/CMakeFiles/CMakeOutput.log".
See also "/home/user-linux/ddb/etcd-cpp-apiv3/build/CMakeFiles/CMakeError.log".

**Comment by WhiteBearWYL** [comment]
在cmake .. 完成后：
user-linux@Robot2:~/ddb/etcd-cpp-apiv3/build$ make -j$(nproc)
[  3%] Running C++ gRPC compiler on /home/user-linux/ddb/etcd-cpp-apiv3/proto/rpc.proto
[  3%] Running C++ gRPC compiler on /home/user-linux/ddb/etcd-cpp-apiv3/proto/v3election.proto
/usr/local/bin/grpc_cpp_plugin: error while loading shared libraries: libgrpc_plugin_support.so.1: cannot open shared object file: No such file or directory
/usr/local/bin/grpc_cpp_plugin: error while loading shared libraries: libgrpc_plugin_support.so.1: cannot open shared object file: No such file or directory
--grpc_out: protoc-gen-grpc: Plugin failed with status code 127.
--grpc_out: protoc-gen-grpc: Plugin failed with status code 127.
proto/CMakeFiles/protobuf_generates.dir/build.make:150: recipe for target 'proto/gen/proto/v3election.grpc.pb.cc' failed
make[2]: *** [proto/gen/proto/v3election.grpc.pb.cc] Error 1
make[2]: *** Waiting for unfinished jobs....
proto/CMakeFiles/protobuf_generates.dir/build.make:133: recipe for target 'proto/gen/proto/rpc.grpc.pb.cc' failed
make[2]: *** [proto/gen/proto/rpc.grpc.pb.cc] Error 1
CMakeFiles/Makefile2:146: recipe for target 'proto/CMakeFiles/protobuf_generates.dir/all' failed
make[1]: *** [proto/CMakeFiles/protobuf_generates.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

另外可以发一下微信群么？

**Comment by sighingnow** [comment]
![image](https://user-images.githubusercontent.com/7144772/209258655-65522e17-bacd-40e3-9889-91cd2cd69a9f.png)

试试

```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/lib64
```

**Comment by WhiteBearWYL** [comment]
在跑测试代码时，使用g++ t.cpp -g -o t -std=c++11 -lpthread -letcd-cpp-api -lprotobuf -lgrpc++ -lgrpc -lz -lcpprest -lssl -lcrypto -lboost_system -I /usr/local/include/etcd/proto/ 显示 /usr/local/lib/libetcd-cpp-api.so 中有多个未定义的引用，这些引用都是grpc相关的，请问我应该怎样修改编译指令？

**Comment by sighingnow** [comment]
You could use CMake to build your testing cases and depends on this repo by `find_package(etcd-cpp-api)`.

You may retrieve the detailed build flags using `make VERBOSE=true`.
