### ISSUE TITLE
Build and Install Instructions are not clear

### ISSUE THREAD

**Issue by sarat-k** [etcd-cpp-apiv3/etcd-cpp-apiv3#2]
Hi,

Is this library usable or just experimental ? The instructions on how to build and install don't even exist.  The commands listed for compiling proto files also don't work as is. Given, the partial information,  here is what I had to do after installing all the dependencies listed on the page:

1. download the source code (or git clone)
2. cd <top-dir>  // the directory where code is cloned
3. cd proto/
4. protoc -I . --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ./rpc.proto
5. protoc -I . --cpp_out=. ./*.proto
6. cd ..
7. cmake .

At this step, I encountered this error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
**CATCH_INCLUDE_DIR**
   used as include directory in directory /home/saratk/etcd-cpp-apiv3/tst

-- Configuring incomplete, errors occurred!
See also "/home/saratk/etcd-cpp-apiv3/CMakeFiles/CMakeOutput.log".

To workaround this problem, I opened CMakeCache.txt file in the same directory and changed the following line

CATCH_INCLUDE_DIR:PATH=CATCH_INCLUDE_DIR-NOTFOUND

to

CATCH_INCLUDE_DIR:PATH=<output of pwd command> and did "cmake ." again

8. make

This step failed with following error

<home-dir>/etcd-cpp-apiv3/v3/src/Action.cpp: In member function ‘void etcdv3::Action::waitForResponse()’:
<home-dir>/etcd-cpp-apiv3/v3/src/Action.cpp:26:36: error: ‘GPR_ASSERT’ was not declared in this scope
   GPR_ASSERT(got_tag == (void*)this);
                                    ^
make[2]: *** [src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/Action.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/etcd-cpp-api.dir/all] Error 2
make: *** [all] Error 2

To workaround, I opened the file Action.cpp and replaced GPR_ASSERT() with assert()

9. make install

At this point header files got installed in /usr/local/include/etcd/ and the library itself got installed as /usr/local/lib/libetcd-cpp-api.so

10. After this I still had to manually copy the header files generated from steps 4 and 5 to /usr/local/include/etcd/

A decent documentation with step-by-step instructions would be nice to begin with to encourage others to use this lib (assuming it works, I haven't come to that yet).

Thanks,
Sarat

**Comment by mauiarches** [comment]
Hello,

This library is useable. However, there are still some features not implemented(e.g. setting of multiple endpoints)

Comments on your compilation issues:
CATCH_INCLUDE_DIR
--> this is the directory where the catch.hpp is located This file is included in this repo. See https://github.com/nokia/etcd-cpp-apiv3/blob/master/catch.hpp

For the GPR_ASSERT error, did you follow the instructions in https://github.com/grpc/grpc/blob/release-0_14/INSTALL.md?

I will add building instructions.

**Comment by sarat-k** [comment]
Hi,

Please see inline ...

On Sun, Dec 11, 2016 at 12:59 PM, mauiarches <notifications@github.com>
wrote:

> Hello,
>
> This library is useable. However, there are still some features not
> implemented(e.g. setting of multiple endpoints)
>

Any approximate timeline for this ?

> Comments on your compilation issues:
> CATCH_INCLUDE_DIR
> --> this is the directory where the catch.hpp is located This file is
> included in this repo. See https://github.com/nokia/etcd-
> cpp-apiv3/blob/master/catch.hpp
>

I was able to get around this one by pointing to this directory.

> For the GPR_ASSERT error, did you follow the instructions in
> https://github.com/grpc/grpc/blob/release-0_14/INSTALL.md?
>

Yes, I did follow the instructions. Here is the "make install" output for
grpc

[eskon@ubuntu:~/grpc]sudo make install
[INSTALL] Installing public C headers
[MAKE]    Generating cache.mk
[STRIP]   Stripping libgpr.a
[STRIP]   Stripping libgrpc.a
[STRIP]   Stripping libgrpc_cronet.a
[STRIP]   Stripping libgrpc_unsecure.a
[INSTALL] Installing C pkg-config files
[INSTALL] Installing libgpr.a
[INSTALL] Installing libgrpc.a
[INSTALL] Installing libgrpc_cronet.a
[INSTALL] Installing libgrpc_unsecure.a
[STRIP]   Stripping libgpr.so.2.0.0-dev
[STRIP]   Stripping libgrpc.so.2.0.0-dev
[STRIP]   Stripping libgrpc_cronet.so.2.0.0-dev
[STRIP]   Stripping libgrpc_unsecure.so.2.0.0-dev
[INSTALL] Installing libgpr.so.2.0.0-dev
[INSTALL] Installing libgrpc.so.2.0.0-dev
[INSTALL] Installing libgrpc_cronet.so.2.0.0-dev
[INSTALL] Installing libgrpc_unsecure.so.2.0.0-dev
[INSTALL] Installing public C++ headers
[STRIP]   Stripping libgrpc++.a
[STRIP]   Stripping libgrpc++_cronet.a
[STRIP]   Stripping libgrpc++_reflection.a
[STRIP]   Stripping libgrpc++_unsecure.a
[INSTALL] Installing C++ pkg-config files
[INSTALL] Installing libgrpc++.a
[INSTALL] Installing libgrpc++_cronet.a
[INSTALL] Installing libgrpc++_reflection.a
[INSTALL] Installing libgrpc++_unsecure.a
[STRIP]   Stripping libgrpc++.so.1.1.0-dev
[STRIP]   Stripping libgrpc++_cronet.so.1.1.0-dev
[STRIP]   Stripping libgrpc++_reflection.so.1.1.0-dev
[STRIP]   Stripping libgrpc++_unsecure.so.1.1.0-dev
[INSTALL] Installing libgrpc++.so.1.1.0-dev
[INSTALL] Installing libgrpc++_cronet.so.1.1.0-dev
[INSTALL] Installing libgrpc++_reflection.so.1.1.0-dev
[INSTALL] Installing libgrpc++_unsecure.so.1.1.0-dev
[INSTALL] Installing grpc protoc plugins
[INSTALL] Installing root certificates

After this I tried to build etcd-cpp-api-v3

[eskon@ubuntu:~/etcd-cpp-apiv3]make
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   locale
--   random
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eskon/etcd-cpp-apiv3
Scanning dependencies of target etcd-cpp-api
*[  3%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/proto/kv.pb.cc.o*
*[  6%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/proto/auth.pb.cc.o*
*[ 10%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/proto/rpc.pb.cc.o*
*[ 13%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/proto/rpc.grpc.pb.cc.o*
[ 16%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncTxnResponse.cpp.o
[ 20%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncRangeResponse.cpp.o
[ 23%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/Transaction.cpp.o
[ 26%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/action_constants.cpp.o
[ 30%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncSetAction.cpp.o
[ 33%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncCompareAndSwapAction.cpp.o
[ 36%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncUpdateAction.cpp.o
[ 40%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncGetAction.cpp.o
[ 43%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncDeleteAction.cpp.o
[ 46%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncCompareAndDeleteAction.cpp.o
[ 50%] Building CXX object
src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/Action.cpp.o
/home/eskon/etcd-cpp-apiv3/v3/src/Action.cpp: In member function ‘void
etcdv3::Action::waitForResponse()’:
/home/eskon/etcd-cpp-apiv3/v3/src/Action.cpp:26:36: error: ‘GPR_ASSERT’ was
not declared in this scope
   GPR_ASSERT(got_tag == (void*)this);
                                    ^
make[2]: *** [src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/Action.cpp.o] Error
1
make[1]: *** [src/CMakeFiles/etcd-cpp-api.dir/all] Error 2
make: *** [all] Error 2
[eskon@ubuntu:~/etcd-cpp-apiv3]

I changed that statement to assert() and moved on, not knowing where to
look for the definition of GPR_ASSERT. Hope that is good enough. Once build
went thru, I did "sudo make install" and see the lib in the right place
(but had to manually copy bunch of header files including v3/include to
/usr/local/include/etcd/v3 (I think make install is missing all these).

Although now I was able to successfully compile and install the lib, I am
unable to use it in my app. When my app is loading I see this error:

*undefined symbol: _ZTVN12etcdserverpb5Watch4StubE*
I am not sure what is going on but from the above build log I see that
proto/etcdserver.pb.cc is not compiled at all. Is this expected ? Where is
this supposed to be used ?

The way I am using it is:

1. There is a 3rd party app that provides some kind of plugin mechanism for
extensions in the form of a shared libraries
2. I am writing one such extension (which is a shared library as mentioned
above), and for now all it does is connects to etcd server

#2 is what I have control on and I am compiling that code as shared library
and this shared library has dependency on etcd-cpp-api-v3 library. So, the
3rd party app is loading my lib and during that time it fails by throwing
above undefined symbol error. Any idea what could be the issue ?

Thanks

**Comment by mauiarches** [comment]
Hi,

Regarding the GPR_ASSERT, it seems they changed the header file to where is it defined. It is now defined in grpc/support/log.h.

For the meantime, you can add #include <grpc/support/log.h> in v3/src/Action.cpp while fix is not yet committed. 

I did "sudo make install" and see the lib in the right place
(but had to manually copy bunch of header files including v3/include to
/usr/local/include/etcd/v3 (I think make install is missing all these).
--> You don't need to add the v3/include files, since only those header files that are indicated in the make file should be used by the client and these are only the header files that will be the interface of the library to the client.

*undefined symbol: _ZTVN12etcdserverpb5Watch4StubE*
I am not sure what is going on but from the above build log I see that
proto/etcdserver.pb.cc is not compiled at all. Is this expected ? Where is
this supposed to be used ?
--> I'm still checking this. BTW, what boost version did you install?

**Comment by sarat-k** [comment]
On Mon, Dec 12, 2016 at 10:19 AM, mauiarches <notifications@github.com>
wrote:

> Hi,
>
> Regarding the GPR_ASSERT, it seems they changed the header file to where
> is it defined. It is now defined in grpc/support/log.h.
>

[SK] Thanks .. will try this and let you know.

> For the meantime, you can add #include <grpc/support/log.h> in
> v3/src/Action.cpp while fix is not yet committed.
>
> I did "sudo make install" and see the lib in the right place
> (but had to manually copy bunch of header files including v3/include to
> /usr/local/include/etcd/v3 (I think make install is missing all these).
> --> You don't need to add the v3/include files, since only those header
> files that are indicated in the make file should be used by the client and
> these are only the header files that will be the interface of the library
> to the client.
>

[SK] Without this, I get a compilation error. The top level file I included
in my code is /usr/local/include/etcd/Client.hpp and that file is including
the following:

#include "v3/include/Transaction.hpp"
#include "v3/include/AsyncTxnResponse.hpp"
#include "v3/include/Action.hpp"

and so my code doesn't compile as it is complaining about these missing
files. So I ended up copy v3/include to /usr/local/include/etcd/

*undefined symbol: _ZTVN12etcdserverpb5Watch4StubE*
> I am not sure what is going on but from the above build log I see that
> proto/etcdserver.pb.cc is not compiled at all. Is this expected ? Where is
> this supposed to be used ?
> --> I'm still checking this. BTW, what boost version did you install?
>

[SK] The boost version I am on is 1.54.0.

I used "nm" on my shared lib to see what other unresolved symbols are there
starting with "etcdserverpb" and see these.

[eskon@ubuntu:~/kea]nm app_hooks.so | grep "etcdserverpb" | grep "U"
                 U _ZTVN12etcdserverpb2KV4StubE
                 U _ZTVN12etcdserverpb5Lease4StubE
                 U _ZTVN12etcdserverpb5Watch4StubE

Thanks,
SK

**Comment by mauiarches** [comment]
Hi,
Regarding the unresolved symbols, did you link your shared library to the etcd-cpp-api shared lib?

**Comment by sarat-k** [comment]
Hi,

Yes I did link with this lib. Here is the command I used:

g++ -std=c++11 -std=gnu++11 -Wno-write-strings -I . -I
/usr/local/include/etcd -L /usr/local/lib *-letcd-cpp-api* -fpic -shared -o
apphooks.so load_unload.cc  apphooks.cc version.cc

The issue seems to be only with few symbols (highlighted below) .. "nm" is
reporting them as U (unresolved)

eskon@ubuntu:~/kea>nm apphooks.so | \grep etcdserverp

0000000000017759 W
_ZSt3getILm1EIPN12etcdserverpb5Watch4StubESt14default_deleteIS2_EEENSt9__add_refINSt13tuple_elementIXT_ESt5tupleIIDpT0_EEE4typeEE4typeERSB_
000000000001760e W
_ZSt3getILm1EJPN12etcdserverpb2KV4StubESt14default_deleteIS2_EEENSt9__add_refINSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeEE4typeERSB_
000000000001786d W
_ZSt3getILm1EJPN12etcdserverpb5Lease4StubESt14default_deleteIS2_EEENSt9__add_refINSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeEE4typeERSB_
0000000000017759 W
_ZSt3getILm1EJPN12etcdserverpb5Watch4StubESt14default_deleteIS2_EEENSt9__add_refINSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeEE4typeERSB_
000000000021e960 V _ZTIN12etcdserverpb2KV13StubInterfaceE
000000000021e940 V _ZTIN12etcdserverpb5Lease13StubInterfaceE
000000000021e950 V _ZTIN12etcdserverpb5Watch13StubInterfaceE
0000000000019940 V _ZTSN12etcdserverpb2KV13StubInterfaceE
00000000000198c0 V _ZTSN12etcdserverpb5Lease13StubInterfaceE
0000000000019900 V _ZTSN12etcdserverpb5Watch13StubInterfaceE
000000000021e4e0 V _ZTVN12etcdserverpb2KV13StubInterfaceE
*                 U _ZTVN12etcdserverpb2KV4StubE*
000000000021e440 V _ZTVN12etcdserverpb5Lease13StubInterfaceE
*                 U _ZTVN12etcdserverpb5Lease4StubE*
000000000021e4a0 V _ZTVN12etcdserverpb5Watch13StubInterfaceE
*                 U _ZTVN12etcdserverpb5Watch4StubE*


The following are the ones that seem to be problematic:

[eskon@ubuntu:~/kea]nm apphooks.so | \grep etcdserverpb  | \grep " U"
                 U _ZTVN12etcdserverpb2KV4StubE
                 U _ZTVN12etcdserverpb5Lease4StubE
                 U _ZTVN12etcdserverpb5Watch4StubE


Thanks,
SK

**Comment by mauiarches** [comment]
> g++ -std=c++11 -std=gnu++11 -Wno-write-strings -I . -I
/usr/local/include/etcd -L /usr/local/lib *-letcd-cpp-api* -fpic -shared -o
apphooks.so load_unload.cc  apphooks.cc version.cc

Can you also try to link with grpc++ shared library

**Comment by mauiarches** [comment]
Hello,

I ran nm in the etcd-cpp-api library and the following are there:

> ZTVN12etcdserverpb2KV4StubE
   ZTVN12etcdserverpb5Lease4StubE
   ZTVN12etcdserverpb5Watch4StubE

**Comment by sarat-k** [comment]
Hi,

I linked to grpc++ but no success. The issue here seems to be that my
shared library (even though compiled with -letcd-cpp-api) is not pulling
this dependency when the final app is running. So, there are two options -
either modify the actual app's makefile to include etcd-cpp-ap.so or use
LD_PRELOAD env variable to launch the app (e.g.,
LD_PRELOAD=/usr/local/lib/libetcd-cpp-ap.so <app>). I tried the later and
the app was able to start fine. I will try to make few etcd calls and see
if things are working or not.

Thanks for all the help.

Regards,
SK

**Comment by sarat-k** [comment]
A quick question ... is the cluster support coming anytime soon ? Right now
we seem to be able to connect to only one etcd endpoint.

Thanks,
SK

**Comment by mauiarches** [comment]
Hi,

No timeline yet. 😟

**Comment by swawibe** [comment]
Hi,
I am trying to run this library. I have used the following commands:

1. git clone ...
2. cd etcd-cpp-apiv3/proto
3. protoc -I . --grpc_out=. --plugin=protoc-gen-grpc=which grpc_cpp_plugin ./rpc.proto
4. protoc -I . --cpp_out=. ./*.proto
5. cd ..
6. cmake .
7. make

```
[  3%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/proto/kv.pb.cc.o
[  7%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/proto/auth.pb.cc.o
[ 10%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/proto/rpc.pb.cc.o
[ 14%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/proto/rpc.grpc.pb.cc.o
[ 17%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncTxnResponse.cpp.o
[ 21%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncRangeResponse.cpp.o
[ 25%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/Transaction.cpp.o
[ 28%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncSetAction.cpp.o
[ 32%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncCompareAndSwapAction.cpp.o
[ 35%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncUpdateAction.cpp.o
[ 39%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncGetAction.cpp.o
[ 42%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncDeleteAction.cpp.o
[ 46%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncCompareAndDeleteAction.cpp.o
[ 50%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/Action.cpp.o
[ 53%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncWatchAction.cpp.o
[ 57%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/V3Response.cpp.o
[ 60%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncDeleteRangeResponse.cpp.o
[ 64%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncWatchResponse.cpp.o
[ 67%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncLeaseGrantResponse.cpp.o
[ 71%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/AsyncLeaseGrantAction.cpp.o
[ 75%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/__/v3/src/KeyValue.cpp.o
[ 78%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/Client.cpp.o
[ 82%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/Response.cpp.o
[ 85%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/Value.cpp.o
[ 89%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/SyncClient.cpp.o
[ 92%] Building CXX object src/CMakeFiles/etcd-cpp-api.dir/Watcher.cpp.o
[ 96%] Linking CXX shared library libetcd-cpp-api.so
[100%] Built target etcd-cpp-api

```

8. sudo make install

```
[100%] Built target etcd-cpp-api
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libetcd-cpp-api.so
-- Set runtime path of "/usr/local/lib/libetcd-cpp-api.so" to ""
-- Up-to-date: /usr/local/include/etcd/Client.hpp
-- Up-to-date: /usr/local/include/etcd/SyncClient.hpp
-- Up-to-date: /usr/local/include/etcd/Response.hpp
-- Up-to-date: /usr/local/include/etcd/Value.hpp
-- Up-to-date: /usr/local/include/etcd/Watcher.hpp
```

9. Now I just tried to initialize etcd client using this code:

```
#include "etcd/Client.hpp" 

int main(){
    etcd::Client etcd("http://127.0.0.1:4001");
    return 0;
}

```
10. My command line command was:

`g++ -std=c++11 -std=gnu++11 -I /usr/local/include/etcd/ -I ~/etcd-cpp-apiv3/ -L/usr/local/lib/* -letcd-cpp-api -o testing.o test.cpp `


But I am getting an error :

```
/tmp/ccmvVYqp.o: In function `main':
test.cpp:(.text+0x1c1): undefined reference to `etcd::Client::Client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccmvVYqp.o: In function `__static_initialization_and_destruction_0(int, int)':
test.cpp:(.text+0x27c): undefined reference to `boost::system::generic_category()'
test.cpp:(.text+0x288): undefined reference to `boost::system::generic_category()'
test.cpp:(.text+0x294): undefined reference to `boost::system::system_category()'
/tmp/ccmvVYqp.o: In function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::details::_TaskInliningMode)':
```

Most probably I need to add few more header files in my test.cpp . Can you please give me an example to run etcd client ?

Thanks

**Comment by danielzhanghl** [comment]
maybe you need link boost as well, below is the command i used to build, which works, only FYI
.
g++  -std=c++11 -std=gnu++11 -I ../../cppapiv3/include -I ../etcd-cpp-api -Wl,-Bdynamic  -L ../../cppapiv3/lib -lgrpc++  -lboost_system  -l cpprest  -L ../../cppapiv3/etcd-cpp-api -letcd-cpp-api       -L /lib64 -lssl -lcrypto  EtcdTest.cpp

**Comment by swawibe** [comment]
Hi @danielzhanghl Thanks for your quick reply. As you have said to linked with boost library, I have modified the command into this :

`g++ -std=c++11 -std=gnu++11 -I v3/include/ -I ../etcd-cpp-apiv3/ -Wl,-Bdynamic -lgrpc++ -lboost_system -l cpprest -L ../etcd-cpp-apiv3/ -letcd-cpp-api -L /lib64/ -lssl -lcrypto -L ~/boost_1_64_0/ -L ~/boost_1_64_0/stage/lib/ test.cpp
`

But unfortunately, still I am getting the same error : 

```
/tmp/ccrtD16r.o: In function `main':
test.cpp:(.text+0x1c1): undefined reference to `etcd::Client::Client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccrtD16r.o: In function `__static_initialization_and_destruction_0(int, int)':
test.cpp:(.text+0x27c): undefined reference to `boost::system::generic_category()'
test.cpp:(.text+0x288): undefined reference to `boost::system::generic_category()'
test.cpp:(.text+0x294): undefined reference to `boost::system::system_category()'
/tmp/ccrtD16r.o: In function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::details::_TaskInliningMode)':
test.cpp:(.text._ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE[_ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE]+0x40): undefined reference to `pplx::get_ambient_scheduler()'
/tmp/ccrtD16r.o: In function `boost::asio::error::get_system_category()':
test.cpp:(.text._ZN5boost4asio5error19get_system_categoryEv[_ZN5boost4asio5error19get_system_categoryEv]+0x5): undefined reference to `boost::system::system_category()'
```

**Comment by danielzhanghl** [comment]
seems your boost did not install system component, refer to the document, they used below boost component.


----------
You can use:
./bootstrap.sh --with-libraries=**system**,thread,locale,random,chrono,regex,filesystem
./b2 install
-

**Comment by mbotner** [comment]
Is this project still being maintained?  I don't see any updates for a year, and I can't get it to build.

**Comment by xianghaiM** [comment]
when i make this library,i got following error.Anyone met this problem?
/usr/local/include/google/protobuf/port_def.inc:540:1: error: ‘PROTOBUF_EXPORT_TEMPLATE_TEST_MSVC_HACK_DEFAULT’ was not declared in this scope
In file included from /usr/local/include/google/protobuf/stubs/strutil.h:41:0,
                 from /usr/local/include/google/protobuf/io/coded_stream.h:14,
                 from /root/etcd-cpp-apiv3/proto/kv.pb.h:23,
                 from /root/etcd-cpp-apiv3/v3/include/KeyValue.hpp:4,
                 from /root/etcd-cpp-apiv3/etcd/Value.hpp:7,
                 from /root/etcd-cpp-apiv3/etcd/Response.hpp:7,
                 from /root/etcd-cpp-apiv3/etcd/Client.hpp:4,
                 from /root/etcd-cpp-apiv3/src/Client.cpp:2:

**Comment by sighingnow** [comment]
Hi @mbotner,
> Is this project still being maintained? I don't see any updates for a year, and I can't get it to build.

The project is now maintained by me.

**Comment by sighingnow** [comment]
After installing cpprest sdk (the latest version), just build this library with cmake should enough.

```
mkdir build && cd build
cmake ..
make -j
```

I will update the build & install doc, and may consider import cpprest sdk as a submodule to help the building process.

**Comment by mbotner** [comment]
Thanks!  Unfortunately, we had to abandon the use of etcd because the
c++ API was so difficult to build.


Mark

**Comment by sighingnow** [comment]
> Thanks! Unfortunately, we had to abandon the use of etcd because the c++ API was so difficult to build. Mark
> […](#)

Now it shouldn't be a problem, with current etcd-cpp-apiv3. I promise :)

**Comment by sighingnow** [comment]
Fixed. In `README.md` there's a section about how to install dependencies and build & install this library.

**Comment by mbotner** [comment]
Thanks!  If I get back to using etcd, I'm sure I'll make use of that.


Mark
