### ISSUE TITLE
The campaign API would be conflicted with AsyncNext

### ISSUE THREAD

**Issue by Kimjin-gd** [etcd-cpp-apiv3/etcd-cpp-apiv3#202]
The campaign API would be blocked until it could be the leader. But if grpc_timeout is set, AsyncNext will be returned when deadline exceed，then campaign will return.

**Comment by sighingnow** [comment]
It is not a bug. Users need to check if the response is ok or an error to acquire the leadership correctly. I have document this behaviour and add a test/example in #205.
