### ISSUE TITLE
get_target_property() called with non-existent target gRPC::grpc_cpp_plugin

### ISSUE THREAD

**Issue by ojayanth** [etcd-cpp-apiv3/etcd-cpp-apiv3#210]
Trying to get etcd-cpp-apiv3  in OpenBMC distribution.  Seeing below build failure.

xxxx/etcd-cpp-apiv3/build$ cmake .. -DCPPREST_EXCLUDE_WEBSOCKETS=ON
-- Toolchain file defaulted to 'xxxx/sysroots/x86_64-oesdk-linux/usr/share/cmake/OEToolchainConfig.cmake'
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: xxxx/sysroots/x86_64-oesdk-linux/usr/bin/arm-openbmc-linux-gnueabi/arm-openbmc-linux-gnueabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: xxxx/sysroots/x86_64-oesdk-linux/usr/bin/arm-openbmc-linux-gnueabi/arm-openbmc-linux-gnueabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Building etcd-cpp-apiv3 with C++11
-- Found Boost: xxxx/sysroots/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/usr/lib/cmake/Boost-1.81.0/BoostConfig.cmake (found version "1.81.0") found components: system thread random 
-- Found OpenSSL:xxxx/sysroots/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/usr/lib/libcrypto.so (found version "3.0.7")  
CMake Warning at xxxx/sysroots/x86_64-oesdk-linux/usr/share/cmake-3.24/Modules/FindProtobuf.cmake:524 (message):
  Protobuf compiler version 3.6.1 doesn't match library version 3.21.5
Call Stack (most recent call first):
  CMakeLists.txt:110 (find_package)

-- Found Protobuf: xxxx/sysroots/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/usr/lib/libprotobuf.so (found version "3.21.5") 
-- Found ZLIB: xxxx/sysroots/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/usr/lib/libz.so (found version "1.2.13") 
-- Found c-ares: xxxx/sysroots/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/usr/lib/cmake/c-ares/c-ares-config.cmake (found version "1.18.0") 
-- Found Threads: TRUE  
-- Found RE2 via CMake.
CMake Error at CMakeLists.txt:124 (get_target_property):
  get_target_property() called with non-existent target
  "gRPC::grpc_cpp_plugin".

-- Found GRPC: gRPC::gpr;gRPC::grpc;gRPC::grpc++,  (found version: "1.53.0")
-- Performing Test W_NO_CPP17_EXTENSIONS
-- Performing Test W_NO_CPP17_EXTENSIONS - Success
-- Configuring incomplete, errors occurred!
See also "xxxx/etcd-cpp-apiv3/build/CMakeFiles/CMakeOutput.log".

Looking for help on debugging this failure.

**Comment by ojayanth** [comment]
As an experiment tried to changed package name gRPC to gRPCPlugin. and build worked. 

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3b96f25..5ef6511 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -118,8 +118,8 @@ if(Protobuf_PROTOC_EXECUTABLE)
     endif()
 endif()
 
-find_package(gRPC QUIET)
-if(gRPC_FOUND)
+find_package(gRPCPlugin QUIET)
+if(gRPCPlugin_FOUND)
     set(GRPC_LIBRARIES gRPC::gpr gRPC::grpc gRPC::grpc++)
     get_target_property(GRPC_CPP_PLUGIN gRPC::grpc_cpp_plugin LOCATION)
     get_target_property(GRPC_INCLUDE_DIR gRPC::grpc INTERFACE_INCLUDE_DIRECTORIES)
@@ -129,7 +129,7 @@ else()
 endif()
 message(STATUS "Found GRPC: ${GRPC_LIBRARIES}, ${GRPC_CPP_PLUGIN} (found version: \"${gRPC_VERSION}\")")
 # avoid use the apt-get installed libgrpc-dev (version v1.13) on Ubuntu 18.04
-if(gRPC_FOUND AND gRPC_VERSION VERSION_LESS "1.14")
+if(gRPCPlugin_FOUND AND gRPC_VERSION VERSION_LESS "1.14")
     message(FATAL_ERROR "gRPC '${gRPC_VERSION}' is not supported, please install a newer gRPC library "
                         "by following the example below"

**Comment by sighingnow** [comment]
Hi @ojayanth, I have just pushed a commit to master branch to prevent such issues. Can you help to check if current master works in your environment?

Thanks!

**Comment by sighingnow** [comment]
Try delete the build directory `build/` and try again.

**Comment by sighingnow** [comment]
> Building in sdk environment. Tried with cloning latest repo with your latest changes. and created build folder and issued cmake .. -DCPPREST_EXCLUDE_WEBSOCKETS=ON
> 
> Seeing same failure mentioned above. should i try getting full build in non sdk environment?

I have just pushed a new commit (https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/commit/91c64e18d325f4b63f0dfbd795c50c9c3ec3d3e0) to main. Could you please help to `git pull` and try again?

Thanks!

**Comment by ojayanth** [comment]
Looks like latest commit fixed .  i can see  xxxx/rootfs/usr/lib/libetcd-cpp-api.so file created successfully.  
Appreciate your help.

**Comment by sighingnow** [comment]
Thanks for helping me for debugging.
