### ISSUE TITLE
Watcher constructor with "from_index" parameter provides with wrong/missing initial events

### ISSUE THREAD

**Issue by wbobillet** [etcd-cpp-apiv3/etcd-cpp-apiv3#212]
There are 2 issues apparently with the watchers when using the constructor
```
Watcher(SyncClient const &client, std::string const & key, int64_t fromIndex,
                       std::function<void(Response)> callback,
                       std::function<void(bool)> wait_callback,
                       bool recursive);
```
I have, with from_index = 26 the following sequence of watch events:

[ WARN] [1682046230.386947856]: REGISTER WATCHER with revision 14
[ WARN] [1682046230.455648620]: RESPONSE with revision 20 : value = watch_2 , version = 4, _values.size() = 0
[ WARN] [1682046230.463006705]: RESPONSE with revision 21 : value = watch_6 , version = 8, _values.size() = 0
[ WARN] [1682046230.474437277]: RESPONSE with revision 22 : value = watch_7 , version = 9, _values.size() = 0
[ WARN] [1682046230.485145775]: RESPONSE with revision 23 : value = watch_8 , version = 10, _values.size() = 0
[ WARN] [1682046230.496025633]: RESPONSE with revision 24 : value = watch_9 , version = 11, _values.size() = 0

obtained with cthe following code 
```
// Watcher creation
_etcd_watcher.reset(new etcd::Watcher(_etcd_client, _key, head_revision, std::move(internal_cb), std::move(wait_cb), _is_recursive));
            std::cout << "[etcd] Watcher set on key " << _key << std::endl;
            ROS_WARN_STREAM("REGISTER WATCHER with revision " << head_revision);


// Callback
EtcdWatchCb internal_cb = [this](etcd::Response resp) -> void {
            if (!resp.is_ok()) {
                ROS_WARN_STREAM("RESPONSE (error) with revision " << resp.index());
                std::cout << "[etcd] Watch failed on '" << _key << "'." << resp.error_message() << ". Error code " << resp.error_code() << std::endl;
                _cb(etcdv3ErrorToWMErrorCode(resp.error_code()), _key, std::nullopt);
                return;
            }
            ROS_WARN_STREAM("RESPONSE with revision " << resp.index() << " : value = " << resp.value().as_string() << " , version = " << resp. << ", _values.size() = " << resp.values().size());
            std::cout << "[etcd] Watch successful on '" << _key << "'. k/v is '" << resp.value().key() << "/" << resp.value().as_string() << ", " << std::endl;
            
            _cb(etcdv3ErrorToWMErrorCode(resp.error_code()), resp.value().key(), std::make_optional(resp.value().as_string()));
        };
```

Nevertheless, etcdctl gives

"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 14
"Version" : 1
"Value" : "init"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 15
"Version" : 2
"Value" : "watch_0"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 16
"Version" : 3
"Value" : "watch_1"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 17
"Version" : 4
"Value" : "watch_2"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 18
"Version" : 5
"Value" : "watch_3"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 19
"Version" : 6
"Value" : "watch_4"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 20
"Version" : 7
"Value" : "watch_5"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 21
"Version" : 8
"Value" : "watch_6"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 22
"Version" : 9
"Value" : "watch_7"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 23
"Version" : 10
"Value" : "watch_8"
"Lease" : 0
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 14
"ModRevision" : 24
"Version" : 11
"Value" : "watch_9"
"Lease" : 0

So 
- versions for revision 14, 15, 16, 17, 18, 19 are missing
- value for answer with revision 20 is false : 'watch_2' instead of 'watch_5' and version 4 instead of 7. Seems like this is the value+version for revision 17.

**Comment by sighingnow** [comment]
Can you show me the complete operation commands that I can used to reproduce the issue?

**Comment by wbobillet** [comment]
@sighingnow Of course

I have 

[ERROR] [1682063461.755348731]: Current index 2
[ERROR] [1682063461.786437317]: Watch 'key watch'. Revision : 3, value = inittt
[ERROR] [1682063461.867941001]: Watch 'key watch'. Revision : 4, value = watch_1
[ERROR] [1682063461.968871998]: Watch 'key watch'. Revision : 5, value = watch_2
[ERROR] [1682063462.069998019]: Watch 'key watch'. Revision : 6, value = watch_3
[ERROR] [1682063462.171258499]: Watch 'key watch'. Revision : 7, value = watch_4
[ERROR] [1682063462.272367583]: Watch 'key watch'. Revision : 8, value = watch_5
[ERROR] [1682063462.373567425]: Watch 'key watch'. Revision : 9, value = watch_6
[ERROR] [1682063462.474754632]: Watch 'key watch'. Revision : 10, value = watch_7
[ERROR] [1682063462.576000042]: Watch 'key watch'. Revision : 11, value = watch_8
[ERROR] [1682063462.677334774]: Watch 'key watch'. Revision : 12, value = watch_9


with the code 

```
   std::string key_watch = "key watch";
    etcd::Client client("127.0.0.1:2379");
    client.put(key_watch, "inittt").get();

    auto current_index = client.head().get().index();
    ROS_ERROR_STREAM("Current index " << current_index);
    auto internal_cb = [&](etcd::Response resp) -> void {
        if (!resp.is_ok()) return;
        ROS_ERROR_STREAM("Watch '" << key_watch << "'. Revision : " << resp.index() << ", value = " << resp.value().as_string());
    };
    auto wait_cb =  [this](bool) {};
    auto w = etcd::Watcher(client, key_watch, current_index, std::move(internal_cb), std::move(wait_cb), false);

    ros::Duration(0.01).sleep();
    for (int i = 0; i < 10; ) {
        std::string value = "watch_" + std::to_string(i++);
        client.put(key_watch, value).get();
        ros::Duration(0.1).sleep();
    }

```

For revision 3 it should be 'watch_0' as you can see with etcdctl

"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 2
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 2
"Version" : 1
"Value" : "inittt"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 3
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 3
"Version" : 2
"Value" : "watch_0"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 4
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 4
"Version" : 3
"Value" : "watch_1"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 5
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 5
"Version" : 4
"Value" : "watch_2"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 6
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 6
"Version" : 5
"Value" : "watch_3"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 7
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 7
"Version" : 6
"Value" : "watch_4"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 8
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 8
"Version" : 7
"Value" : "watch_5"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 9
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 9
"Version" : 8
"Value" : "watch_6"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 10
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 10
"Version" : 9
"Value" : "watch_7"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 11
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 11
"Version" : 10
"Value" : "watch_8"
"Lease" : 0
"ClusterID" : 14841639068965178418
"MemberID" : 10276657743932975437
"Revision" : 12
"RaftTerm" : 2
"Type" : PUT
"Key" : "key watch"
"CreateRevision" : 2
"ModRevision" : 12
"Version" : 11
"Value" : "watch_9"
"Lease" : 0

**Comment by wbobillet** [comment]
In the previous example I had some delays so that only the value of the first event issue is considered

**Comment by sighingnow** [comment]
Which verison of etcd-cpp-apiv3 you are working with?

**Comment by sighingnow** [comment]
I can see why some events are lost in your case. Actually, a response in the watcher callback is a set of events, rather than a single event. You need the following callback:

```
auto internal_cb = [&](etcd::Response resp) -> void {
      if (!resp.is_ok()) {
        std::cout << "Error: " << resp.error_message() << std::endl;
        return;
      }
      for (auto const &event: resp.events()) {
        std::cout << "Watch '" << event.kv().key()
                  << "'. ModifedRevision : " <<  event.kv().modified_index()
                  << "', Vision : " <<  event.kv().version()
                  << ", value = " << event.kv().as_string() << std::endl;
      }
  };
```

Which will yield the same output as etcdctl.
