### ISSUE TITLE
Watcher re-connection issue

### ISSUE THREAD

**Issue by ka9j3** [etcd-cpp-apiv3/etcd-cpp-apiv3#218]
when I used the README.MD demo code.

void wait_for_connection(etcd::Client &client) {
  // wait until the client connects to etcd server
  while (!client.head().get().is_ok()) {
    sleep(1);
  }
}

the program was coredump in `client.head().get().is_ok()`

Is that a bug?

**Comment by sighingnow** [comment]
Could you please paste the complete example code that can reproduce the failure? Thanks!
