### ISSUE TITLE
Watcher lost connections with two clients (connects to two etcd instances) in the same process

### ISSUE THREAD

**Issue by wbobillet** [etcd-cpp-apiv3/etcd-cpp-apiv3#219]
Basically I have an appli with 2 clients, connected to 2 etcd (2 etcd::Clients), say etcd1 and etcd2. The stores are not in the same cluster (run as mono instance in docker containers, 1 node per cluster).

problem: When I shut down etcd1 all the watchers of etcd2 are cancelled and restarted  !

The error 14 is raised from etcd1 client, but how come it can affect the other ? Is it sth in common with gRPC ?

Thanks in advance

**Comment by sighingnow** [comment]
Do you have to different etcd instance and compose them into the same etcd cluster?

Can you share the piece of code about how you
- setup those two clients
- how you setup those watchers
- and how you close/shutdown the first etcd client?

**Comment by wbobillet** [comment]
> Do you have to different etcd instance and compose them into the same etcd cluster?
> 
> Can you share the piece of code about how you
> 
>     * setup those two clients
> 
>     * how you setup those watchers
> 
>     * and how you close/shutdown the first etcd client?

Basically, I run 2 etcd in isolated containers. Each etcd is its own cluster (so 1 etcd per cluster only). The shutdown is realized by stopping the docker container. The 2 clients are created based on the IPv4 of each etcd (using Docker local network).

**Comment by sighingnow** [comment]
Let me understand the case, you have two etcd, e.g., http://etcd-1:2379 and http://etcd-2:2379, and two watchers are created as 

```cpp
// ...
auto watcher1 = etcd::Watcher("http://etcd-1:2379;http://etcd-2:2379", "key", callback)

// ...
auto watcher2 = etcd::Watcher("http://etcd-1:2379;http://etcd-2:2379", "key", callback);
```

And when you stop etcd-1, the watcher 2 is triggered for reconnect as well, right?

If the above assumption is true, it is a known issue that multi-endpoints doesn't work very well for failover for watcher and keepalive (see also: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/134).

**Comment by sighingnow** [comment]
As a workaround, you use use different endpoints order to initialize those two different client to avoid the second reconnect.

```cpp
// ...
auto watcher1 = etcd::Watcher("http://etcd-1:2379;http://etcd-2:2379", "key", callback)

// ...
auto watcher2 = etcd::Watcher("http://etcd-2:2379;http://etcd-1:2379", "key", callback);
```

**Comment by sighingnow** [comment]
And if the two etcd instances belong to two isolated clusters, you should never use both endpoints to the same client...

**Comment by wbobillet** [comment]
> And if the two etcd instances belong to two isolated clusters, you should never use both endpoints to the same client...

This is the point, 2 different clients also are used !!!! But still the second one has its watchers wait callbacks called with the cancelled flag. 
The clients only have in common that they live in the same application. So I was wondering if sth in the gRPC library, maybe a static thing, can be the cause of this.

**Comment by sighingnow** [comment]
Could you please share the code/minimal example that can reproduce the issue?\

Failed to reproduce the error with the following code:

```cpp
TEST_CASE("create two watcher")
{
  etcd::Watcher w1("http://127.0.0.1:24799", "/test", printResponse, true);
  etcd::Watcher w2("http://127.0.0.1:25799", "/test", printResponse, true);

  std::this_thread::sleep_for(std::chrono::seconds(120));
}
```

**Comment by sighingnow** [comment]
Closing as lack of response from the end-user and the issue itself cannot be reproduced.
