### ISSUE TITLE
Which version of grpc do you recommend for v0.14.3

### ISSUE THREAD

**Issue by sinFunc** [etcd-cpp-apiv3/etcd-cpp-apiv3#222]
hello, i would like to know how to choose the appropriate version of grpc for this project .Hoping to your reply .thanks!

**Comment by sighingnow** [comment]
Any version of gRPC>=1.14 should work: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/CMakeLists.txt#L130-L137

Newer version would be better, I think.

**Comment by sinFunc** [comment]
Thank you so much! and do you know how to compile this project ,so that i can use ectd-cpp-api.a without any dependence.
