### ISSUE TITLE
 Unknown CMake command "use_cxx".

### ISSUE THREAD

**Issue by LazyPlanet** [etcd-cpp-apiv3/etcd-cpp-apiv3#226]
hi，我现在在执行测试用例：etcd-cpp-apiv3/tst/build
报错如下：

CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as   project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found unit_test - AuthTest
**CMake Error at CMakeLists.txt:23 (use_cxx):
  Unknown CMake command "use_cxx".**

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.26)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by sighingnow** [comment]
You need use the root directory as the source dir for cmake, `src` or `tst` is just a submodule.

Try

```
cd etcd-cpp-apiv3/
mkdir build
cd build
cmake ..
make -j
```

**Comment by LazyPlanet** [comment]
如果在这里，则报错这个：
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Building etcd-cpp-apiv3 with C++11
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")  
CMake Error at /usr/local/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  _**Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)**_
Call Stack (most recent call first):
  /usr/local/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.26/Modules/FindProtobuf.cmake:650 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:109 (find_package)

**Comment by LazyPlanet** [comment]
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)

**Comment by LazyPlanet** [comment]
CentOs下安装教程
1.安装grpc按照官方教程一步步安装即可，
教程地址：https://grpc.io/docs/languages/cpp/quickstart/
2.安装protobuf
grpc安装路径问题，要自行编译protobuf，进入1.中下载的grpc目录中的protobuf，
比如：grpc/third_party/protobuf/build进行编译make && make install
