### ISSUE TITLE
Is it a typo of Readme?

### ISSUE THREAD

**Issue by learscnuli** [etcd-cpp-apiv3/etcd-cpp-apiv3#229]
![image](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/13833278/4fcf2635-5003-4541-bab5-3f163e9c007a)

I can not understand this behavior. 
"/test/key1" does not have the prefix "/test/new_dir".
Is it a typo?

**Comment by sighingnow** [comment]
Fixed.
