### ISSUE TITLE
Linker errors when building test executables

### ISSUE THREAD

**Issue by SumuduLansakara** [etcd-cpp-apiv3/etcd-cpp-apiv3#23]
I am trying to use etcd-cpp-apiv3 on Linux to build a etcd client. I was testing with a sample application but it is failing at the linking stage. I get similar link errors when building etcd-cpp-apiv3 test executables too.

Truncated output:
```
...
[ 87%] Building CXX object tst/CMakeFiles/LockTest.dir/LockTest.cpp.o
[ 89%] Linking CXX executable ../bin/WatcherTest
[ 91%] Linking CXX executable ../bin/LockTest
[ 92%] Linking CXX executable ../bin/EtcdTest
[91m/usr/bin/ld: /usr/local/lib/libgpr.a(log_linux.cc.o): in function `gpr_default_log(gpr_log_func_args*)':
log_linux.cc:(.text+0x1e1): undefined reference to `bool absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Dispatch<char const*>(absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Data, absl::lts_2020_02_25::str_format_internal::FormatConversionSpec, void*)'
/usr/bin/ld: log_linux.cc:(.text+0x1f0): undefined reference to `bool absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Dispatch<int>(absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Data, absl::lts_2020_02_25::str_format_internal::FormatConversionSpec, void*)'
/usr/bin/ld: log_linux.cc:(.text+0x268): undefined reference to `bool absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Dispatch<long>(absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Data, absl::lts_2020_02_25::str_format_internal::FormatConversionSpec, void*)'
/usr/bin/ld: log_linux.cc:(.text+0x27f): undefined reference to `absl::lts_2020_02_25::str_format_internal::FormatPack[abi:cxx11](absl::lts_2020_02_25::str_format_internal::UntypedFormatSpecImpl, absl::lts_2020_02_25::Span<absl::lts_2020_02_25::str_format_internal::FormatArgImpl const>)'
/usr/bin/ld: /usr/local/lib/libgpr.a(global_config_env.cc.o): in function `grpc_core::GlobalConfigEnvBool::Get()':
global_config_env.cc:(.text+0x196): undefined reference to `bool absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Dispatch<char const*>(absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Data, absl::lts_2020_02_25::str_format_internal::FormatConversionSpec, void*)'
/usr/bin/ld: global_config_env.cc:(.text+0x1cb): undefined reference to `absl::lts_2020_02_25::str_format_internal::FormatPack[abi:cxx11](absl::lts_2020_02_25::str_format_internal::UntypedFormatSpecImpl, absl::lts_2020_02_25::Span<absl::lts_2020_02_25::str_format_internal::FormatArgImpl const>)'
/usr/bin/ld: /usr/local/lib/libgpr.a(global_config_env.cc.o): in function `grpc_core::GlobalConfigEnvInt32::Get()':
global_config_env.cc:(.text+0x2ea): undefined reference to `bool absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Dispatch<char const*>(absl::lts_2020_02_25::str_format_internal::FormatArgImpl::Data, absl::lts_2020_02_25::str_format_internal::FormatConversionSpec, void*)'
/usr/bin/ld: global_config_env.cc:(.text+0x31f): undefined reference to `absl::lts_2020_02_25::str_format_internal::FormatPack[abi:cxx11](absl::lts_2020_02_25::str_format_internal::UntypedFormatSpecImpl, absl::lts_2020_02_25::Span<absl::lts_2020_02_25::str_format_internal::FormatArgImpl const>)'
/usr/bin/ld: /usr/local/lib/libgrpc++.a(client_context.cc.o): in function `grpc::ClientContext::set_call(grpc_call*, std::shared_ptr<grpc::Channel> const&)':
client_context.cc:(.text+0x332): undefined reference to `grpc_call_cancel_with_status'
/usr/bin/ld: client_context.cc:(.text+0x34b): undefined reference to `grpc_call_cancel'
/usr/bin/ld: /usr/local/lib/libgrpc++.a(client_context.cc.o): in function `grpc::ClientContext::TryCancel()':
client_context.cc:(.text+0x452): undefined reference to `grpc_call_cancel'
/usr/bin/ld: /usr/local/lib/libgrpc++.a(client_context.cc.o): in function `grpc::ClientContext::peer[abi:cxx11]() const':
client_context.cc:(.text+0x4b8): undefined reference to `grpc_call_get_peer'
/usr/bin/ld: /usr/local/lib/libgrpc++.a(client_context.cc.o): in function `grpc::ClientContext::~ClientContext()':
client_context.cc:(.text+0x929): undefined reference to `grpc_call_unref'
...
```

I have prepared a Dockerfile to illustrate the exact steps I took.
- [Dockerfile.txt](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/files/5541469/Dockerfile.txt)
- [docker_build.log](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/files/5541470/docker_build.log)

(This shows only the steps upto building test executables. I believe the link errors I get for my sample application are the same).

I hope I am not doing something wrong as I was following the README ([this](https://qiita.com/YujiroTakahashi/items/de5dbd67e2f77ee465c8) guide also helped). I really appreciate if someone can have a look and advice a fix/workaround. Even though the complete recreation steps are in the Dockerfile, I would gladly provide more details if needed.

**Comment by sighingnow** [comment]
If I understand correctly you are working with a static-linked grpc library. Current `CMakeLists.txt` doesn't handle such cases since grpc has a tons of dependencies, which can be either "bundled" or "package". I have noticed that you are working with Ubuntu, thus I think `apt-get install libgrpc-dev libgrpc++-dev libprotobuf-dev libssl-dev libz-dev protobuf-compiler-grpc` should works, just as what we have done in `https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-test.yml`.

Maunally build latest grpc is not need for etcd-cpp-apiv3. This library could work well with a wide range of grpc, even very old  versions.

**Comment by SumuduLansakara** [comment]
Thanks a lot @sighingnow for the quick response. Indeed you are right, all the problems were related to grpc static lib. Your proposal to install dependancies via the package manager worked perfectly (and it saved a lot of time by avoiding compilation of all the dependent libs). This is my working [Dockerfile](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/files/5546224/Dockerfile.txt) in case it helps anyone.
@sighingnow I appreciate your help very much ! My problem is solved and this issue can be closed.

**Comment by sighingnow** [comment]
Thanks for verifying the solution so quickly @SumuduLansakara , happy coding!

**Comment by grants** [comment]
how to compile etcd-cpp-api.so, I always got etcd-cpp-api.a ? thx @sighingnow

**Comment by sighingnow** [comment]
@grants Thanks for your interest on this library, you could follow https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/eee2ea2d14dfd6ea4ba0d8c77fad24b041e3bac7/.github/workflows/build-test.yml#L35-L82 for how to install dependencies and build the library.

**Comment by grants** [comment]
Thank you, I got it.
