### ISSUE TITLE
How can I get the keys in the directory without subdirectories?

### ISSUE THREAD

**Issue by learscnuli** [etcd-cpp-apiv3/etcd-cpp-apiv3#230]
Suppose that We have the etcd key:
```
/test/Axxx
/test/Axxx/test1/xxx1
/test/Bxxxx
/Test/Bxxxx/test2/xxx2
/test/Cxxxx
/Test/Cxxxx/test3/xxx3

```

how can I get the keys in /test only? 
( /test/Axxx, /test/Bxxxx, /test/Cxxxx)

Seems that ls("/test/") will return the keys in the subdirectories, it's not meet our expectations.

if we use API "pplx::task<Response> ls(std::string const & key, std::string const &range_end, size_t const limit);"
I can not provide the "range_end" value.

thanks for your help in advance.

**Comment by sighingnow** [comment]
No way. See also: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/151#issuecomment-1218904961

**Comment by sighingnow** [comment]
See also: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/157#issuecomment-1256846848
