### ISSUE TITLE
Support fetch_and_like semantics

### ISSUE THREAD

**Issue by sighingnow** [etcd-cpp-apiv3/etcd-cpp-apiv3#234]

**Comment by SuhailAhmedVelorum** [comment]
Is there support to perform get operations within transactions to get a snapshot of all the keys required at a particular time? Getting the keys individually could pose problems if changes are propagated to the target machine during the series of get operations.

**Comment by sighingnow** [comment]
Will be fixed in the next two or three days. The transaction part needs refactor to provide more high-level APIs.

**Comment by sighingnow** [comment]
Example and documentation has been added in #236
