### ISSUE TITLE
Undefined reference to Client::client

### ISSUE THREAD

**Issue by Nivekiba** [etcd-cpp-apiv3/etcd-cpp-apiv3#237]
Hello, I wanted to use this library to interact with etcd cluster.
I follow all the steps (building all intermediates needed dependencies) of the README.md and when I try to run a sample program

`etc.cc`
```
#include <chrono>
#include <iostream>
#include <thread>

#include "etcd/Client.hpp"

int main(){
        etcd::Client etcd("http://127.0.0.1:4001");
    return 0;
}
```

Here is the command I typed (command line produced after reading many issues) and the output I got

```
root@node0:/users/nivekiba# g++ -std=c++11 -std=gnu++11 -I /usr/local/include/etcd/ -I ./etcd-cpp-apiv3/ -I ./etcd-cpp-apiv3/include/ -L ./etcd-cpp-apiv3/ -L/usr/local/lib/* -letcd-cpp-api -o testing.o etc.cc -lgrpc++ -lboost_system
/usr/bin/ld: /tmp/ccpZgOjk.o: in function `main':
etc.cc:(.text+0xdf): undefined reference to `etcd::Client::Client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: etc.cc:(.text+0x120): undefined reference to `etcd::Client::~Client()'
/usr/bin/ld: /tmp/ccpZgOjk.o: in function `pplx::details::_TaskCollectionImpl::_RunTask(void (*)(void*), void*, pplx::details::_TaskInliningMode)':
etc.cc:(.text._ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE[_ZN4pplx7details19_TaskCollectionImpl8_RunTaskEPFvPvES2_NS0_17_TaskInliningModeE]+0x44): undefined reference to `pplx::get_ambient_scheduler()'
collect2: error: ld returned 1 exit status
```

Does anyone have the possible solution to this ?

**Comment by sighingnow** [comment]
If you use `BUILD_ETCD_CORE_ONLY=ON` during configuring cmake, the async client `Client` won't be available.

**Comment by Nivekiba** [comment]
I did not set that option. In the README.md it's said it's set to `OFF` by default

**Comment by Nivekiba** [comment]
It was a weird problem, 
Just need to add `-lcpprest -letcd-app-api` to the build options.

But I have a question, is it possible (the easiest way) to include this repo as a dependency of a project which already uses `cmake` and `ninja` to build ?

**Comment by sighingnow** [comment]
With cmake, you could either

- clone this project, make install, and `find(package etcd-cpp-api)` in your CMakeLists.txt
- or, use `add_subdirectory(...)` to add this project as submodule.

**Comment by sighingnow** [comment]
> Just need to add -lcpprest -letcd-app-api to the build options.

Closing as resolved.

**Comment by Nivekiba** [comment]
Hello, @sighingnow 
Sorry to bounce again on this post,
I tried to include etcd-cpp-api in a project built with cmake and ninja (ceph) but I still get the `undefined reference` error I posted above.

I use the `find_package` command during the cmake prepare phase the package is well found but during the build the `undefined reference` error appeared

**Comment by sighingnow** [comment]
You need link the etcd-cpp-apiv3 library to your library/executable like:

```cmake
target_link_libraries(<Your Library / Executable> PRIVATE etcd-cpp-api)
```
