### ISSUE TITLE
etcd::KeepAlive constructor bug

### ISSUE THREAD

**Issue by Wuhao-9** [etcd-cpp-apiv3/etcd-cpp-apiv3#241]
当构造函数的参数lease_id指定为0或不指定时，库中的注释说运行时库会自动分配一个lease，但事实上没有自动分配id，id仍然是0.

**Comment by sighingnow** [comment]
Try `client.leasekeepalive()` as a workaround.

**Comment by sighingnow** [comment]
Closing as fixed in main.
