### ISSUE TITLE
how to use etcd::KeepAlive?

### ISSUE THREAD

**Issue by MeiCorl** [etcd-cpp-apiv3/etcd-cpp-apiv3#246]
![image](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/13530545/7f9d2c52-3b74-4901-bf77-bb7165018295)

Help, what's wrong with my code, the same to the examples.

**Comment by MeiCorl** [comment]
![image](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/13530545/84eec89d-90a5-4aaa-8dbe-ca74c08970a4)
got this error during building.

**Comment by sighingnow** [comment]
Include "etcd/KeepAlive.hpp" would fixes the error.

**Comment by sighingnow** [comment]
And, you should be a magic value `1` as the lease_id (the fourth argument). It should be response from `leasegrant`.

**Comment by sighingnow** [comment]
Closing.
