### ISSUE TITLE
keepalive 如何定时的续租

### ISSUE THREAD

**Issue by LazyPlanet** [etcd-cpp-apiv3/etcd-cpp-apiv3#247]
大佬好：
我想定时的续租某个key，现在设定是5s的定时器，续租leaseid 10s，问题是5s定时器经常超过5s调用，导致有时候续租失败，提示ttl已经是0了。是不是不能如此使用或者keepalive中有固定等待时间？谢谢。代码如下：

定时器：
![image](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/15156350/fd6f47b9-5881-44b9-b14b-408c81dd0421)

定期续租：
![image](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/15156350/88b3c299-136e-4716-aeee-be287893d4cc)

**Comment by sighingnow** [comment]
KeepAlive的逻辑是这样的：

- leasegrant(ttl): 表示向etcd 申请一个过期时间是 ttl 的lease
- KeepAlive(ttl, lease_id)：会每隔 max(ttl-1, 1) 秒 刷新一下 lease id: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/src/KeepAlive.cpp#L175

所以，传给 KeepAlive 的 ttl 要小于或等于传给 leasegrant 的 TTL

**Comment by sighingnow** [comment]
更简单的做法，你可以不 leasegrant, 而是传给 KeepAlive 0，会自动创建lease，

```cpp
etcd::KeepAlive keepalive(*etcdPtr, handler, 10, 0);
auto lease_id = keepalive.Lease();
```

图中你的 KeepAlive 使用也有问题，KeepAlive 应该是创建一次，保持它不被析构，而是每次创建一个新对象， 
KeepAlive 中有后台线程自动refresh。

如果你想实现自己手动出发refresh的逻辑，目前没有暴露这样的 API...

**Comment by LazyPlanet** [comment]
谢谢解答，我不是想自己刷新，如果有这种就可以满足我的要求了。因为我要做service，希望lease_id是不变的，因此我以为要自己续租，目前看是需要的，我只是DoKeepAlive的时候check下状态就行了应该。
现在改成在初始化的时候，
(1) 创建：
m_keepalive = m_etcdPtr->leasekeepalive(10).get();
(2) 定时检查即可了：
![image](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/15156350/a1f8170d-2b56-4b19-9154-3e898e5b2f58)

再次感谢大佬解答，谢谢。

**Comment by sighingnow** [comment]
> 这样就可以了吧？

可以的。

**Comment by sighingnow** [comment]
Closing as resolved.

**Comment by sighingnow** [comment]
> 如果m_etcdPtr断了，就导致异常what(): Etcd authentication failed: Socket closed。

这个应该是bug，需要被fix。可以重新新开个issue么，就后面这个问题

**Comment by LazyPlanet** [comment]
> > 如果m_etcdPtr断了，就导致异常what(): Etcd authentication failed: Socket closed。
> 
> 这个应该是bug，需要被fix。可以重新新开个issue么，就后面这个问题

好的，谢谢大佬。
