### ISSUE TITLE
Sync api 编译问题

### ISSUE THREAD

**Issue by czln** [etcd-cpp-apiv3/etcd-cpp-apiv3#265]
README里面表示通过 `BUILD_ETCD_CORE_ONLY`可以控制编译同步和异步的库，但是我看到现在的cmake里面已经没有这个option了。

以及，尽管同步接口不需要boost和cpprest，但是在cmake里面却有全局的头文件include：

`etcd/CMakeLists.txt:153:`
``` cmake

include_directories(SYSTEM ${Boost_INCLUDE_DIR}
                           ${CPPREST_INCLUDE_DIR}
                           ${PROTOBUF_INCLUDE_DIRS}
                           ${GRPC_INCLUDE_DIR}
                           ${OPENSSL_INCLUDE_DIR})
```

**Comment by sighingnow** [comment]
这个option有的：https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/CMakeLists.txt#L31

**Comment by sighingnow** [comment]
> 以及，尽管同步接口不需要boost和cpprest，但是在cmake里面却有全局的头文件include：

Worth to be fixed.

**Comment by czln** [comment]
sry，是我搞错了，确认了一下，cmake没有什么问题，是我这边的库是旧的，但是参考的是你们新的README。
