### ISSUE TITLE
Behavior mismatch on add operation

### ISSUE THREAD

**Issue by daniel0076** [etcd-cpp-apiv3/etcd-cpp-apiv3#266]
Hi team, 

I recently encountered a behavior mismatch on the `add` operation. 
Where in the header file it states the behavior of [`add`](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/etcd/SyncClient.hpp#L341
) is:  `Creates a new key and sets it's value. Fails if the key already exists.`

**However, given the key is duplicated, the value is still overwritten.** 

## Reproduction steps:

The can be reproduced by modifying the test cases in [EtcdSyncTest](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/tst/EtcdSyncTest.cpp#L21).
By changing the value in `Key already exists` case from 42 to 9999 or something different than 42.
Also the test case itself is problematic as it can't reflect if the value is overwritten or not after the second `add` operation with the same key.

**My environment:**

+ Linux Ubuntu 22.04.1 (x86)
+ etcd-cpp-apiv3 commit hash: #ba62163
+ etcd version: 3.3.15

**Result screenshot:**
<img width="500" alt="Screenshot 2024-03-12 at 00 21 35" src="https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/assets/6964535/3e23f2f0-c210-4b1a-8ff4-09d21e8be6af">

 **Fix**
I have inspected the change logs and discover that this might be caused by a refactor work on 2023-07-15.
The behavior changed after the commit [#153546f96](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/commit/153546f9654e1f08f177c11f31ac24ed94000443#diff-cb901b6729bfc224a99d32ace315d2b3647bcdb42c4417dbc073129e82ed2055L954)
I can also confirm that fallback to tag `v0.15.0` also solves the issue.

I have made a MR to fix the issue by aligning with old behavior and also update the test cases.
Best

**Comment by sighingnow** [comment]
Closing as #267 has been merged. Thank you @daniel0076 !
