### ISSUE TITLE
Waiting for lock not to return

### ISSUE THREAD

**Issue by huangxinze** [etcd-cpp-apiv3/etcd-cpp-apiv3#269]
When using 10 processes to simultaneously request locks, only 2 were returned, while the remaining 8 were waiting and unable to return. (Note: The two returned have already released the lock)

```
    auto response = m_pEtcdClient->lock(etcdGetLockKey(nGroupID)).get();
    if (response.is_ok()) {
        logE("get lock success");
        strLockKey = response.lock_key();
        logE("lock key is " + strLockKey);
        return true;
    }
    logE("get lock failure");
```

```
log:
etcdAcquireLock
etcdAcquireLock
etcdAcquireLock
etcdAcquireLock
etcdAcquireLock
get lock success
lock key is Lock/53001/32908e35e3921a55
etcdAcquireLock
etcdAcquireLock
etcdAcquireLock
etcdAcquireLock
etcdAcquireLock
get lock success
lock key is Lock/53001/32908e35e3921a56
```

```
    logI("etcdInitSequenceID");

    // get lock
    std::string strLockKey = "";
    if (etcdAcquireLock(nGroupID, strLockKey) == false) {
        logW("get etcd lock failure");
        return false;
    }

    // increase sequenceid
    m_lSequenceID = etcdGetSequenceID(nGroupID);
    logI("sequenceid is " + std::to_string(m_lSequenceID));

    // release lock
    etcdReleaseLock(strLockKey);

    return true;
```

```
    logI("etcdReleaseLock");

    // check etcd client.
    if (m_pEtcdClient == nullptr) {
        logE("m_pEtcdClient is nullptr");
        return;
    }

    // unlock
    auto response = m_pEtcdClient->unlock(strLockKey).get();
    if (response.is_ok()) {
        logI("release lock success");
    } else {
        logW("release lock failure");
    }
```

**Comment by huangxinze** [comment]
After rebooting the cluster node of ETCD, it was restored and returned to normal

**Comment by huangxinze** [comment]
操作步骤是这样的：进程启动的时候，我会去请求一个lock, 然后获得lock之后 会去put一个数据，put完成之后 会释放这个lock。

问题表现是：单进程操作没有异常，一旦开启 100个进程同时并发开启和关闭，然后一共8个脚本，800个进程 同时去不停反复的 开启和关闭。一旦某个脚本100个进程 请求获取锁的时候，另外其他脚本还在处理锁的时候，这个时候 进程kill掉。 然后就会出现 前一次的启动产生的锁 只能等待超时才能被释放，反复这样操作之后，锁就会产生堆积。然后就无法注册，哪怕等待所有的锁超时，全部释放掉了之后，这个时候并发10个进程去获取锁，就会出现这个异常，只有重启了etcd服务节点后 才能恢复。

**Comment by sighingnow** [comment]
Please make sure you are using the lock_key returned by the `lock()` API to call `unlock()`. See also: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3?tab=readme-ov-file#lock .

We have a unittest for concurrent lock as well: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/tst/LockTest.cpp
