### ISSUE TITLE
test failed: SIGFPE - Floating point error signal

### ISSUE THREAD

**Issue by grants** [etcd-cpp-apiv3/etcd-cpp-apiv3#27]
I ran the test after compile and install:
`./bin/EtcdSyncTest`
and output is:
```
FAILED: 
due to a fatal error condition:
     SIGFPE - Floating point error signal
```
Any suggestions? Thx.

**Comment by sighingnow** [comment]
hi @grants could you please provides more detail about how to reproduce the error above, e.g., OS version, etcd version, c++ compiler version.

**Comment by grants** [comment]
OS version : ubuntu 18.04
etcd version: 3.2
c++ compiler version: g++ 7.0
And I compiled grpc from the source code.

**Comment by sighingnow** [comment]
I think it is the bug in grpc library distributed on Ubuntu 18.04. We also see bug report on upstream grpc respository: https://github.com/grpc/grpc/issues/18948, https://github.com/grpc/grpc/issues/21989.

That means, grpc install by `apt-get install` on Ubuntu 18.04 cannot works for anything.

**Comment by sighingnow** [comment]
> And I compiled grpc from the source code.

May I know the grpc version that you build from source?

**Comment by grants** [comment]
I cloned GRPC version is v1.16.x (branch).

**Comment by sighingnow** [comment]
Hi @grants, I'm not sure what happens to v1.16.x on ubuntu 18.04, but now I confirmed that grpc v1.27.x works well on Ubuntu 18.04. Please refer to our CI for [detailed environment settings](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-test.yml#L47).

Feel free to reopen if you have any further questions.
