### ISSUE TITLE
Compilation error on Ubuntu

### ISSUE THREAD

**Issue by keshpa** [etcd-cpp-apiv3/etcd-cpp-apiv3#271]
The issue very trivial I think at a cursory glance but it's a compilation error since all warnings are errors:

/cpprestsdk/Release/src/http/common/http_helpers.cpp:91:43: error: ‘%8zX’ directive output may be truncated writing between 8 and 16 bytes into a region of size 9 [-Werror=format-truncation=]
   91 |         snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
      |                                           ^~~~
/cpprestsdk/Release/src/http/common/http_helpers.cpp:91:42: note: directive argument in the range [1, 18446744073709551615]
   91 |         snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
      |                                          ^~~~~~
/cpprestsdk/Release/src/http/common/http_helpers.cpp:91:17: note: ‘snprintf’ output between 9 and 17 bytes into a destination of size 9
   91 |         snprintf(buffer, sizeof(buffer), "%8zX", bytes_read);
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I changed the buffer local variable to be of size 17 bytes and changed  "%8zX" =>  "%16zX".

**Comment by sighingnow** [comment]
It is not an issue of the etcd-cpp-apiv3 library itself, rather, it is an issue of the project cpprestsdk.

Please try to open a new issue in their repo: https://github.com/microsoft/cpprestsdk
