### ISSUE TITLE
built  with BUILD_WITH_NO_EXCEPTIONS failed

### ISSUE THREAD

**Issue by mkzz115** [etcd-cpp-apiv3/etcd-cpp-apiv3#278]
As I said，I built with BUILD_WITH_NO_EXCEPTIONS, but occur some errors.

https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/272#issuecomment-2217124311

**Comment by sighingnow** [comment]
Closing as duplicated with #272.
