### ISSUE TITLE
我在 Windows 里面的 WSL ( Ubuntu) 上 git 代码之后，make 出现问题，请问这是什么原因导致的，是 WSL 的文件系统的原因吗？

### ISSUE THREAD

**Issue by Anta-Bear** [etcd-cpp-apiv3/etcd-cpp-apiv3#282]

**Comment by Anta-Bear** [comment]
提示的错误是 ，找不到对应的 .proto 文件，可是文件确实是在我所对应的路径下。

**Comment by 7lingyuan** [comment]
> 提示的错误是 ，找不到对应的 .proto 文件，可是文件确实是在我所对应的路径下。

我也是，您解决了吗？😭

**Comment by Anta-Bear** [comment]
> > 提示的错误是 ，找不到对应的 .proto 文件，可是文件确实是在我所对应的路径下。
> 
> 我也是，您解决了吗？😭

没解决，估计是 WSL 文件系统的问题，还是老老实实装虚拟机吧 hhhh

**Comment by sighingnow** [comment]
Closing as the issue is unrelated with this project itself.
