### ISSUE TITLE
[need to fix] 

### ISSUE THREAD

**Issue by zhangxiaocheng152** [etcd-cpp-apiv3/etcd-cpp-apiv3#32]
In README.md :

Keep alive
Keep alive for leases is implemented using a seperate class KeepAlive, which can be used as:

  etcd::KeepAlive keepalive(etcd, lease_id, ttl);  ==> change to:  etcd::KeepAlive keepalive(etcd, ttl, lease_id);
It will perform a periodly keep-alive action before it is cancelled explicitly, or destructed implicitly.

In CMakeLists.txt
install (FILES ${CMAKE_CURRENT_SOURCE_DIR}/etcd/Client.hpp
               ${CMAKE_CURRENT_SOURCE_DIR}/etcd/SyncClient.hpp
               ${CMAKE_CURRENT_SOURCE_DIR}/etcd/Response.hpp
               ${CMAKE_CURRENT_SOURCE_DIR}/etcd/Value.hpp
               ${CMAKE_CURRENT_SOURCE_DIR}/etcd/Watcher.hpp
               ${CMAKE_CURRENT_SOURCE_DIR}/etcd/KeepAlive.hpp   # add
               DESTINATION include/etcd)

Thx 
最终依然需要感谢，提供了这个客户端。这段就中文了。再次感谢。

**Comment by sighingnow** [comment]
Hi @zhangxiaocheng152 ,

Thanks for noticing that bug! Will be fixed now.
