### ISSUE TITLE
Etcd client get throws "Username is empty"

### ISSUE THREAD

**Issue by kesisci** [etcd-cpp-apiv3/etcd-cpp-apiv3#33]
Hi,
I am creating an instance of client and successfully authenticate, however, when I am trying to get with key, I got "etcdserver: username is empty" error.

**Comment by sighingnow** [comment]
Hi @kesisci,

Could you provide more information about the environment settings, e.g., etcd version, os version, etc.

**Comment by sighingnow** [comment]
Hi @kesisci,

I have added a section of how to properly enable etcd's v3 authentication for early versions of etcd: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#etcd-authentication.

Feel free to reopen if that doesn't resolve your issue.
