### ISSUE TITLE
Compilation fails with: google/api/http.pb.h: No such file or directory

### ISSUE THREAD

**Issue by ashish-billore** [etcd-cpp-apiv3/etcd-cpp-apiv3#37]
I followed the instructions to build and install the etcd-cpp-apiv3 package on Ubuntu 18.04 following the steps:

- https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#requirements
- https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#build-and-install

Build and install completed successfully without errors.
 
After that I created a test program like this, following snippet from [here](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#usage)

```
 ...
  etcd::Client etcd("http://127.0.0.1:2379");
  etcd::Response response = etcd.get("/test/key1").get();
  std::cout << response.value().as_string();
 ...

```

I try to compile like this:
`
g++ test.cpp -o test_etcd -lpthread -letcd-cpp-api -lprotobuf  -lgrpc++ -lgrpc -lz -lcpprest -lssl -lcrypto -lboost_system`

However, I get error like this:

```
In file included from /usr/local/include/etcd/proto/rpc.pb.h:34:0,
                 from /usr/local/include/etcd/proto/rpc.grpc.pb.h:7,
                 from /usr/local/include/etcd/Client.hpp:11,
                 from test.cpp:1:
/usr/local/include/etcd/proto/google/api/annotations.pb.h:28:10: fatal error: google/api/http.pb.h: No such file or directory
 #include "google/api/http.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I already installed proto and grpc libs and expected it to work, can anyone suggest what is missing here?

**Comment by ashish-billore** [comment]
I see this file does exists, still build fails for not finding it:
```
root@lb-prof:~/etcd# ls -ltrh /usr/local/include/etcd/proto/google/api/http.pb.h
-rw-r--r-- 1 root root 61K Jan 31 21:44 /usr/local/include/etcd/proto/google/api/http.pb.h
root@lb-prof:~/etcd# 
```

**Comment by sighingnow** [comment]
Hi @ashish-billore,

Assuming you are installing etcd-cpp-apiv3 library into `/usr/local`, you need to add `/usr/local/include` as well as `/usr/local/include/etcd` to the compiler flags, as

```bash
g++ -I/usr/local/include -I/usr/local/include/etcd
```

That is a bit annoying, but the fixes is not very easy. We want to keep the same package name, module name and file structures with etcd ifself (that means, when we update protobuf files, we just need to copy them, without any changes). The include path in headers is generated by protoc, not ourself. I think adding a nother include directory should be usually fine enough.

**Comment by sighingnow** [comment]
> Wondering, if this is right way or expected while using etcd-cpp-apiv3 in any program.

Assuming you are working with CMake, you just need to add another include directory.

**Comment by ashish-billore** [comment]
Thanks @sighingnow I'll follow your suggestion to compile with:

`g++ -I/usr/local/include -I/usr/local/include/etcd`

**Comment by sighingnow** [comment]
Hi @ashish-billore,

I would like to know if providing a cmake module to make `find_package(etcd)` work and set a CMake variable `ETCD_INCLUDE_DIRS` helps for you case.

**Comment by ashish-billore** [comment]
Sure, that sounds good too.

**Comment by ashish-billore** [comment]
@sighingnow After compiling as above, when I try to run the application, I get a core dump.
I create another issue for that: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/40 since the compilation is done.
Please have a look, thanks!
