### ISSUE TITLE
etcd-cpp-apiv3 with TLS and certs

### ISSUE THREAD

**Issue by ashish-billore** [etcd-cpp-apiv3/etcd-cpp-apiv3#39]
I am trying to find an equivalent way of accessing etcd server which has TLS and certs configured:

```
In case ETCD is configured with TLS certificates support:

ETCDCTL_API=3 etcdctl --endpoints <etcd_ip>:2379 --cacert <ca_cert_path> --cert <cert_path> --key <cert_key_path> get / --prefix --keys-only
```

I could find the info related to [auth with user/password](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/README.md#etcd-authentication). 

Can anyone suggest the equivalent API/function in etcd-cpp-apiv3?

**Comment by sighingnow** [comment]
Hi @ashish-billore,

Authenticate using cartificates is not supported yet. Currently only user/password has been implementation.

That will be done in the next one or two month, but no promise.

**Comment by ashish-billore** [comment]
Thanks for the info, I'll await this feature eagerly.
This is one of the requirement for our current usage.
Thanks!

**Comment by sighingnow** [comment]
> Thanks for the info, I'll await this feature eagerly.
> This is one of the requirement for our current usage.
> Thanks!

Hi @ashish-billore TLS and certs support have been added in #42, please refer to [README](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3#transport-security) for how to use that feature.
