### ISSUE TITLE
The demo you gave is wrong

### ISSUE THREAD

**Issue by zhangwuliang** [etcd-cpp-apiv3/etcd-cpp-apiv3#4]
Demo:

    etcd::Client etcd("http://127.0.0.1:4001");
    pplx::task<etcd::Response> response_task = etcd.get("/test/key1").get();
     // ... do something else
    etcd::Response response = response_task.get();
    std::cout << response.value().as_string();

Hi， as you give above, line two:

     1. etcd.get("keyname")  should return type pplx::task<etcd::Response>
     2. etcd.get("keyname").get()  should return type  etcd::Response 
So, the correct code of line two should be :
   
    etcd::Response response_task = etcd.get("/test/key1").get();

**Comment by sighingnow** [comment]
Fixed. Thanks for your attention on this project!
