### ISSUE TITLE
Floating point exception (core dumped) on running the compiled app

### ISSUE THREAD

**Issue by ashish-billore** [etcd-cpp-apiv3/etcd-cpp-apiv3#40]
I compiled the etcd-cpp-apiv3 lib and below code following steps here: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/37

Test Program:

cat test.cpp 

```
#include <etcd/Client.hpp>
#include <etcd/Response.hpp>
#include <string>
#include <iostream>

int main()
{
  
  std::cout << "Hello";
  etcd::Client etcd("http://127.0.0.1:2379");
  etcd::Response response = etcd.get("/test/key1").get();
  std::cout << response.value().as_string();
  return 0;
}
```
Compile:

`g++ test.cpp -o test_etcd -lpthread -letcd-cpp-api -lprotobuf -lgrpc++ -lgrpc -lz -lcpprest -lssl -lcrypto -lboost_system`

Run:
```

 ./test_etcd 
Floating point exception (core dumped)
```

Event though the above key can be accessed using etcdctl:

```
ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 get /test/key1
/test/key1
value1

```

Any thoughts what might be missing/wrong?

**Comment by sighingnow** [comment]
Hi @ashish-billore,

Could you please provide me more details about the environment settings?

It looks like you are working on Ubuntu 18.04 and using grpc installed by apt-get. That is known not work. For Ubuntu 18.04, you need to build a higher version of grpc from source.

**Comment by sighingnow** [comment]
May duplicate with https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/25.

**Comment by ashish-billore** [comment]
> Hi @ashish-billore,
> 
> Could you please provide me more details about the environment settings?
> 
> It looks like you are working on Ubuntu 18.04 and using grpc installed by apt-get. That is known not work. For Ubuntu 18.04, you need to build a higher version of grpc from source.

Yes, you are right, I am using Ubuntu 18.04 LTS with apt-get provided grpc.
Thanks for the links and info, from https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/27 I see it should work with 
grpc v1.27.x
I'll check with that, thanks!

**Comment by sighingnow** [comment]
> > Hi @ashish-billore,
> > Could you please provide me more details about the environment settings?
> > It looks like you are working on Ubuntu 18.04 and using grpc installed by apt-get. That is known not work. For Ubuntu 18.04, you need to build a higher version of grpc from source.
> 
> Yes, you are right, I am using Ubuntu 18.04 LTS with apt-get provided grpc.
> Thanks for the links and info, from #27 I see it should work with
> grpc v1.27.x
> I'll check with that, thanks!

You could the detailed build & install instructions from https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-test.yml#L47.

**Comment by ashish-billore** [comment]
thanks, I'll refer to that.
