### ISSUE TITLE
watching at a compacted revision doesn't gets canceled

### ISSUE THREAD

**Issue by haow3** [etcd-cpp-apiv3/etcd-cpp-apiv3#43]
Per etcd api document, watching at a compacted revision should get a response from etcd server that this watch has been canceled. However, this cpp api is not honoring that and will continue to watch for responses, and will get stuck in case of a synchronous call. The problem occur at two code places.

1. etcdv3::AsyncWatchAction::waitForResponse(), for the "watch" method of etcd::Client. When watching at a compacted revision, it will get a response with latest revision in header (which is greater than parameters.revision), empty events, and "canceled" field set to true. This will fall to the else case of line 86, and gets stuck there because etcd server will not send any further response.

Expected behavior: it should check for reply.canceled() before line 66 , and cancel the watch if it is set to true.

64     if(got_tag == (void*)this) // read tag
 65     {
 66       if ((reply.created() && reply.header().revision() < parameters.revision) ||
 67           reply.events_size() > 0) {
 68         // we stop watch under two conditions:
 69         //
 70         // 1. watch for a future revision, return immediately with empty events set
 71         // 2. receive any effective events.
 72         isCancelled = true;
 73         stream->WritesDone((void*)"writes done");
 74         grpc::Status status;
 75         stream->Finish(&status, (void *)this);
 76         cq_.Shutdown();
 77
 78         // leave a warning if the response is too large and been fragmented
 79         if (reply.fragment()) {
 80           std::cerr << "WARN: The response hasn't been fully received and parsed" << std::endl;
 81         }
 82       }
 83       else
 84       {
 85         // otherwise, start next round read-reply
 86         stream->Read(&reply, (void*)this);
 87       }-
 88     }

2. etcdv3::AsyncWatchAction::waitForResponse(std::function<void(etcd::Response)> callback), for the watcher class. Watching at a compacted revision will return a response with no events. Thus, similar to above case, it will not handle this response properly, and will keep trying to read from stream.

Expected behavior: it should check for reply.canceled() before line 128 , and cancel the watch if it is set to true. Additionally, the watcher class needs a way to know if it has been canceled by the server.  Consider adding following method to the watcher class:
bool etcd::Watcher::Canceled()
{
  return call->Cancelled();
}

Also, the Cancelled() method needs to grab lock before accessing isCancelled:
 bool etcdv3::AsyncWatchAction::Cancelled() const {
+  std::lock_guard<std::mutex> scope_lock(this->protect_is_cancalled);
   return isCancelled;
 }

126     else if(got_tag == (void*)this) // read tag
127     {
128       if(reply.events_size())
129       {
130         // for the callback case, we don't stop immediately if watching for a future revison,
131         // we wait until there are some expected events.
132         auto resp = ParseResponse();
133         auto duration = std::chrono::duration_cast<std::chrono::microseconds>(
134             std::chrono::high_resolution_clock::now() - start_timepoint);
135         callback(etcd::Response(resp, duration));-
136         start_timepoint = std::chrono::high_resolution_clock::now();
137       }
138       stream->Read(&reply, (void*)this);
139     }

**Comment by sighingnow** [comment]
Thanks for letting me know such feature. I will invistage that tomorrow.

**Comment by sighingnow** [comment]
Fixed. Thanks for noticing such cases.
