### ISSUE TITLE
etcdv3::AsyncGetAction::AsyncGetAction always sort results

### ISSUE THREAD

**Issue by haow3** [etcd-cpp-apiv3/etcd-cpp-apiv3#44]
The etcdv3::AsyncGetAction::AsyncGetAction() method has hardcoded sort target of KEY and sort order of ASCEND. Can we make this optional? It may affect the "ls" performance on a large data set, if user doesn't care about ordering.

12   if(parameters.withPrefix)
 13   {
 14     std::string range_end(parameters.key);-
 15     int ascii = (int)range_end[range_end.length()-1];
 16     range_end.back() = ascii+1;
 17
 18     get_request.set_range_end(range_end);
 19     get_request.set_sort_target(RangeRequest::SortTarget::RangeRequest_SortTarget_KEY);
 20     get_request.set_sort_order(RangeRequest::SortOrder::RangeRequest_SortOrder_ASCEND);
 21   }

**Comment by sighingnow** [comment]
Agree, that will be done soon.

**Comment by sighingnow** [comment]
I just drop the hard-coded sort options and leave it to users :)
