### ISSUE TITLE
The range_end setting for prefix match is incorrect

### ISSUE THREAD

**Issue by haow3** [etcd-cpp-apiv3/etcd-cpp-apiv3#45]
Per etcd document, to get all keys with a prefix, the range_end should be key plus one, (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"). However, the below cpp api implementation is not handling the "a\xff" case properly:
  
 14     std::string range_end(parameters.key);-
 15     int ascii = (int)range_end[range_end.length()-1];
 16     range_end.back() = ascii+1;

Compare it to the official Go clientv3 implementation:

func getPrefix(key []byte) []byte {
	end := make([]byte, len(key))
	copy(end, key)
	for i := len(end) - 1; i >= 0; i-- {
		if end[i] < 0xff {
			end[i] = end[i] + 1
			end = end[:i+1]
			return end
		}
	}
	// next prefix does not exist (e.g., 0xffff);
	// default to WithFromKey policy
	return noPrefixEnd
}

**Comment by sighingnow** [comment]
GOOD catch @haow3 ! Will be fixed now.
