### ISSUE TITLE
list/delete/watch API on range.

### ISSUE THREAD

**Issue by sighingnow** [etcd-cpp-apiv3/etcd-cpp-apiv3#50]
The list/delete/watch gRPC API support range request (i.e., specifying the `range_end` field). In current implementation the `range_end` is generated by `prefix`, which is aligned with etcdctl. But we do could make it more flexible.

The feature is requested by the library user with the following case:

> Is it possible to watch a “range” of keys? Ie. if we have keys from k1, k2, .... k9, k10, all under a prefix, would it be possible to create an etcd::Watcher class that only watches keys k1, k2, k3, ie in the range k1 - k3? Without watching the rest of the keys in this prefix?

**Comment by austinben** [comment]
Hello, with the new changes, would it be possible to create a Watcher Class with the range functionality, so users can indefinitely watch a range of keys, and provide a callback function as needed? As defined in `etcd/Watcher.cpp`.

**Comment by sighingnow** [comment]
> Hello, with the new changes, would it be possible to create a Watcher Class with the range functionality, so users can indefinitely watch a range of keys, and provide a callback function as needed? As defined in `etcd/Watcher.cpp`.

Now the `Watcher` class supports `range_end` as well.

**Comment by austinben** [comment]
Hello, while trying to return list on a range with `range_end` as \0, the etcd::Response returns error 100, key not found.

I am trying to use the functionality described in the etcd v3.4 API as follows: 

"If range_end is ‘\0’, the range is all keys greater than or equal to the key argument."

An example of how I am attempting to use this: 

```c++
etcd::SyncClient etcd(addr);

etcd.set("/test/key2", "val2");
etcd.set("/test/key3", "val3");
etcd.set("/test/key4", "val4");
etcd.set("/test/key5", "val5");
etcd.set("/test/key6", "val6");

etcd::Response list_response = etcd.ls("/test/key4", "");

```

After this, I believe `list_response` should contain 3 keys, `/test/key4`, `/test/key5` and `/test/key6`.

Please let me know if there is an issue with my usage, or if this can be accomplished in a different way. Thank you.

**Comment by sighingnow** [comment]
> After this, I believe `list_response` should contain 3 keys, `/test/key4`, `/test/key5` and `/test/key6`.
> 
> Please let me know if there is an issue with my usage, or if this can be accomplished in a different way. Thank you.

I believe the set range_end as `"\xC0\x80"` could do the trick, note that C++ treat `{'\0'}` as empty string, thus we use the UTF-8's NULL.

**Comment by austinben** [comment]
Thank you for clarifying that! 

I have another question regarding the functionality of this. From my understanding of the API, I believe setting `range_end` to `NULL`, it would return all keys >= to `key` _that are prefixed by_ `key`. 

Currently, it seems to return all keys >= `key`, regardless of prefix. 

For example, based on the following:

```C++
etcd::SyncClient etcd(addr);

etcd.set("/test/key2", "val2");
etcd.set("/test/key3", "val3");
etcd.set("/test/key4", "val4");
etcd.set("/test/key5", "val5");
etcd.set("/test/key6", "val6");
etcd.set("/test2/", "test2value");

etcd::Response list_response = etcd.ls("/test/key4", "");
```
The key/value pair `/test2/ test2value` should not be returned to `list_response` as the prefix does not match `/test/`.

Is there some way to return all keys >= to the specified `key` prefix only? i.e, in the above example, I wish to only return `/test/key4`, `/test/key5` and `/test/key6`.

 I am unsure if this is currently supported with etcd v3 API. If so, how would one accomplish this?

**Comment by sighingnow** [comment]
`etcd.ls("/test/key4", "")` equals to `etcd.get("/test/key4")`. When `range_end` is empty string it won't be set.

> it would return all keys >= to key that are prefixed by key.

If I understand it correctly you need `all keys >= key` and prefixed by `key[0:-1]`, rather than prefixed by `key`?

> Is there some way to return all keys >= to the specified key prefix only? i.e, in the above example, I wish to only return /test/key4, /test/key5 and /test/key6.

You could do `etcd.ls("/tmp/key4", etcdv3::detail::string_plus_one("/tmp/key"))`.

The `string_plus_one` could be found at https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/3e30c4c61d840659a9c2e16a996a7b9d5e9568ab/src/v3/Action.cpp#L41. It hasn't been exposed yet and I could do that, if it helps.

**Comment by austinben** [comment]
> If I understand it correctly you need all keys >= key and prefixed by key[0:-1], rather than prefixed by key?

Yes, in the previous example, I would want to return all keys >= `/test/key4`, prefixed by `/test/`, effectively _not_ returning the key prefixed by `/test2/` as it does not match the original prefix. Sorry for the poor explanation. 

> It hasn't been exposed yet and I could do that, if it helps.

This would be greatly appreciated. Please let me know if you need any more clarification.

**Comment by sighingnow** [comment]
> > It hasn't been exposed yet and I could do that, if it helps.
> 
> This would be greatly appreciated. Please let me know if you need any more clarification.
> 
> **_Update:_** After modifying `range_end` as described in the `string_plus_one`, I have been able to successfully return what I needed. I appreciate that insight!

Has been exposed and tested by #56.
