### ISSUE TITLE
Range RPC Support

### ISSUE THREAD

**Issue by pyssling** [etcd-cpp-apiv3/etcd-cpp-apiv3#57]
Any chance of adding support for the Range RPC? I see we already have the RangeResponse, but not the RangeRequest.

**Comment by sighingnow** [comment]
> but not the RangeRequest.

See: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/src/v3/AsyncGetAction.cpp

And more discussion about range request here: https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/50

**Comment by pyssling** [comment]
Thanks!
