### ISSUE TITLE
I can't install protobuf-compiler-grpc. it is really a package？

### ISSUE THREAD

**Issue by aether-rootr** [etcd-cpp-apiv3/etcd-cpp-apiv3#58]
![image](https://user-images.githubusercontent.com/20625707/116668427-ffcecf00-a9cf-11eb-88d2-ed98fddd28e8.png)

**Comment by sighingnow** [comment]
For Ubuntu 16.04 users, please install grpc by following [the official guide](https://grpc.io/blog/installation/).

AFAIK the package `protobuf-compiler-grpc` is only available since Ubuntu 18.04, and [it is broken][https://github.com/grpc/grpc/issues/21989] on Ubuntu 18.04.

**Comment by sighingnow** [comment]
For Ubuntu 18.04 and Ubuntu 20.04, please refer to the setting process in [CI workflow](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-test.yml).
