### ISSUE TITLE
Clerical error

### ISSUE THREAD

**Issue by BAMSHK** [etcd-cpp-apiv3/etcd-cpp-apiv3#63]
![image](https://user-images.githubusercontent.com/40750078/120298859-04ebaa80-c2fd-11eb-83cc-eb97b03bf369.png)

**Comment by BAMSHK** [comment]
Clerical error

**Comment by sighingnow** [comment]
Thanks! Will fix that soon.

**Comment by sighingnow** [comment]
Fixed.
