### ISSUE TITLE
Can euqal be compared against 'version' instead of 'mod_version'?

### ISSUE THREAD

**Issue by BAMSHK** [etcd-cpp-apiv3/etcd-cpp-apiv3#70]
![image](https://user-images.githubusercontent.com/40750078/122961237-c9ea0d80-d3b6-11eb-8ca5-35f789de8b7d.png)

**Comment by sighingnow** [comment]
There's another overload of `init_compare` which compares against the `mod_version`, I think that is what you need.

https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/6704b9373f5a6f474845fc307309604dcd7db34b/src/v3/Transaction.cpp#L37-L44

**Comment by sighingnow** [comment]
Close as lacking of further response.
