### ISSUE TITLE
Could NOT find OpenSSL

### ISSUE THREAD

**Issue by gitlijian** [etcd-cpp-apiv3/etcd-cpp-apiv3#71]
some machine have not this
if add 
sudo apt install libssl-dev in readme file 
that is better!
![image](https://user-images.githubusercontent.com/15320599/123505411-8d0d6780-d691-11eb-992b-f51ac53ee340.png)

**Comment by sighingnow** [comment]
Thanks for reporting, would you mind adding such a pull request to fix that?

**Comment by gitlijian** [comment]
something is not work when&nbsp;step by step follows your steps,
I guess some environment are different，
but you do not write it.



---Original---
From: "Tao ***@***.***&gt;
Date: Mon, Jun 28, 2021 09:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [etcd-cpp-apiv3/etcd-cpp-apiv3] Could NOT find OpenSSL (#71)




 
Thanks for reporting, would you mind adding such a pull request to fix that?

**Comment by sighingnow** [comment]
For more detailed settings on Ubuntu you could refer to https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/master/.github/workflows/build-test.yml.
