### ISSUE TITLE
windows 10 vcpkg build failed

### ISSUE THREAD

**Issue by zjmnssy** [etcd-cpp-apiv3/etcd-cpp-apiv3#72]
at windows 10, i use vcpkg build , but it run failed.

this is cmd run info:

D:\third_party\vcpkg>vcpkg install etcd-cpp-apiv3
Computing installation plan...
The following packages will be built and installed:
    etcd-cpp-apiv3[core]:x86-windows -> 0.2.1
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\z\AppData\Local\vcpkg\archives\72\7228f5c7dd3969b04f5f1fb8d94d3e38da16c05ca65a9571c842bcc760cebdb4.zip
Starting package 1/1: etcd-cpp-apiv3:x86-windows
Building package etcd-cpp-apiv3[core]:x86-windows...
-- Using D:/third_party/vcpkg/downloads/etcd-cpp-apiv3-etcd-cpp-apiv3-v0.2.1.tar.gz
-- Cleaning sources at D:/third_party/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.2.1-85b6180791.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/third_party/vcpkg/downloads/etcd-cpp-apiv3-etcd-cpp-apiv3-v0.2.1.tar.gz
-- Using source at D:/third_party/vcpkg/buildtrees/etcd-cpp-apiv3/src/v0.2.1-85b6180791.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/third_party/vcpkg/downloads/tools/cmake-3.20.2-windows/cmake-3.20.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: D:/third_party/vcpkg/buildtrees/etcd-cpp-apiv3/x86-windows-dbg
    See logs for more information:
      D:\third_party\vcpkg\buildtrees\etcd-cpp-apiv3\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:104 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/etcd-cpp-apiv3/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package etcd-cpp-apiv3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: etcd-cpp-apiv3:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.

**Comment by sighingnow** [comment]
Thanks, I will try latest version on Windows ASAP.

**Comment by mathisloge** [comment]
Just came from https://github.com/microsoft/vcpkg/issues/18901

So this isn't the recommended way of adding a vcpkg port. Maybe you should consider adding this library as a PR to vcpkg. 
If you need help, I can add the PR. 

The general issue with the build is that the port boost-asio is missing.

**Comment by sighingnow** [comment]
The original error has been fixed after adding `boost-asio` to the dependency list.

**Comment by zjmnssy** [comment]
i found a other problem, after build success, i use the output DLL files, but exe always load dll failed, it said not found the module, so does the build dll is not available？

**Comment by mathisloge** [comment]
It depends. The dll have to be in the same directory as the exe. 
If you get link errors, thats another case.

**Comment by zjmnssy** [comment]
i let the dll and exe at the same directory, but also load failed, the i use dll analyse exe to see what in the dll files, the dll file can't be open , said it a invalid dll file.

**Comment by mathisloge** [comment]
then something is off with your build. Build for me perfectly fine.

**Comment by zjmnssy** [comment]
> then something is off with your build. Build for me perfectly fine.
> Remember to also put abseil and protobuf dlls in you workdir
> ![image](https://user-images.githubusercontent.com/13556116/125475219-e7fb87a0-62cf-45d8-bd6f-ffe8176ca3e8.png)

i also build success, in my D:\third_party\vcpkg\installed\x64-windows\bin , i also have the three dll files you show, i means when i use QT to load the etcd-cpp-api.dll failed, i don't know why.
this is my QT code:

int etcd::Init() {
    QLibrary myLib(QStringLiteral("etcd-cpp-api.dll"));
    if(!myLib.load()){
        qDebug()<<"Load dll failed = " << myLib.errorString();
        return -1;
    }
    qDebug()<<"Load dll success!";
    return 0;
}

**Comment by mathisloge** [comment]
All dlls must be in the same place as the generated exe.

so, copy the "etcd-cpp-api.dll, abseil protobuf, etc. to your executable dir. 
if you have done that, it should load and some debug string should appear.

**Comment by zjmnssy** [comment]
![image](https://user-images.githubusercontent.com/21244667/125548846-91e5d260-7297-4684-a4f3-489c07e3decd.png)

etcd-cpp-api.dll, abseil protobuf, all in the exe path, but also load etcd-cpp-api.dll failed, said it said not found the module;

**Comment by sighingnow** [comment]
```
qDebug()<<"Load dll failed = " << myLib.errorString();
```

@zjmnssy May I know the error string?

**Comment by sighingnow** [comment]
I think you need to makesure the directory that contains those libs is in your `PATH` environment on windows (and `LD_LIBRARY_PATH` on Linux/Mac) then the dynamic library loader can find it..

**Comment by mathisloge** [comment]
You are also passing a relative path to the load function. The relative path resolving takes the current working dir (the path showed left in your console). Try a absolute path. If it works, you need to adjust your work dir

**Comment by zjmnssy** [comment]
when i use  relative path use , QT exe 
qDebug()<<"Load dll failed = " << myLib.errorString(); 
like this:
Load dll failed =  "Cannot load library etcd-cpp-api.dll: 找不到指定的模块。"

when i use  absolute path use , QT exe 
qDebug()<<"Load dll failed = " << myLib.errorString(); 
like this:
Load dll failed =  "Cannot load library D:\\work\\1-code\\1-QT\\qtTools\\bin\\etcd-cpp-api.dll: 找不到指定的模块。"

**Comment by sighingnow** [comment]
Have you put `D:\work\1-code\1-QT\qtTools\bin` to `$PATH`?

**Comment by sighingnow** [comment]
And please try to use `addLibraryPath` to add the directory  `D:\work\1-code\1-QT\qtTools\bin` before load the library with `QLibrary`.

**Comment by sighingnow** [comment]
Please refer to https://stackoverflow.com/questions/28298507/qt-qcoreapplication-addlibrarypath-use as well.

**Comment by zjmnssy** [comment]
i put D:\work\1-code\1-QT\qtTools\bin to system $PATH, and the in QT add ,
``` 
QApplication a(argc, argv);
 a.addLibraryPath(QStringLiteral("D:/work/1-code/1-QT/qtTools/bin"));
```
but also 
Load dll failed =  "Cannot load library etcd-cpp-api.dll: 找不到指定的模块。"

**Comment by zjmnssy** [comment]
did this issue has been closed ?  @sighingnow

**Comment by sighingnow** [comment]
I did't close this issue, but I believe this it is not a etcd-cpp-apiv3 bug. Instead, I think it is a environment setting issue.

For example, I believe etcd-cpp-apiv3.dll depends on cpprest.dll, but i'm not sure it presents in your `$PATH` as well.

**Comment by sighingnow** [comment]
Close as invalid.

**Comment by qugang** [comment]
> did this issue has been closed ? @sighingnow

changge CMakeLists.txt 29 lines option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
copy etcd-cpp-api.lib to vcpkg\installed\x64-windows\debug\lib
After recompiling, solve the problem!

windows need lib and dll  or use LoadLibrary and  GetProcAddress load dll

**Comment by sighingnow** [comment]
> > did this issue has been closed ? @sighingnow
> 
> changge CMakeLists.txt 29 lines option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
> copy etcd-cpp-api.lib to vcpkg\installed\x64-windows\debug\lib
> After recompiling, solve the problem!
> 
> windows need lib and dll or use LoadLibrary and GetProcAddress load dll

That is indeed a different issue.
