### ISSUE TITLE
vcpkg build out etcd-cpp-api.dll when use, always load failed

### ISSUE THREAD

**Issue by zjmnssy** [etcd-cpp-apiv3/etcd-cpp-apiv3#75]
i use QT to load the etcd-cpp-api.dll failed, i don't know why.
this is my QT code:
```
int etcd::Init() {
    QLibrary myLib(QStringLiteral("etcd-cpp-api.dll"));
    if(!myLib.load()){
        qDebug()<<"Load dll failed = " << myLib.errorString();
        return -1;
    }
    qDebug()<<"Load dll success!";
    return 0;
}
```

when i use relative path , QT exe
qDebug()<<"Load dll failed = " << myLib.errorString();
like this:
Load dll failed = "Cannot load library etcd-cpp-api.dll: 找不到指定的模块。"

when i use absolute path , QT exe
qDebug()<<"Load dll failed = " << myLib.errorString();
like this:
Load dll failed = "Cannot load library D:\work\1-code\1-QT\qtTools\bin\etcd-cpp-api.dll: 找不到指定的模块。"

**Comment by sighingnow** [comment]
Close as duplicated with #72
