### ISSUE TITLE
import library in clion project using cmake on macOs

### ISSUE THREAD

**Issue by xtrashild** [etcd-cpp-apiv3/etcd-cpp-apiv3#77]
I installed the required dependencies via brew:
-boost 1.76.0
-openssl@1.1 1.1.1k
-grpc 1.38.1
-protobuf 3.17.3

cpprestsdk didn't build (mac got unresponsive for a very long time) 
so I installed cpprestsdk via brew as mentioned on their repo
-cpprestsdk 2.10.18

I built etcd-cpp-api-v3 and got the library installed
/usr/local/include/etcd/Client.hpp
/usr/local/include/etcd/KeepAlive.hpp
/usr/local/include/etcd/SyncClient.hpp
/usr/local/include/etcd/Response.hpp
/usr/local/include/etcd/Value.hpp
/usr/local/include/etcd/Watcher.hpp
/usr/local/include/etcd/kv.pb.h
/usr/local/include/etcd/v3/Transaction.hpp
/usr/local/include/etcd/v3/txn.pb.h
/usr/local/lib/cmake/etcd-cpp-api/FindGRPC.cmake
/usr/local/lib/cmake/etcd-cpp-api/etcd-cpp-api-config.cmake
/usr/local/lib/cmake/etcd-cpp-api/etcd-cpp-api-config-version.cmake
/usr/local/lib/cmake/etcd-cpp-api/etcd-targets.cmake
/usr/local/lib/cmake/etcd-cpp-api/etcd-targets-release.cmake
/usr/local/lib/libetcd-cpp-api.dylib

Then in my project I tried to get the library via  "find_package(etcd-cpp-api)" but got this warning:

CMake Warning at CMakeLists.txt:22 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/etcd-cpp-api/etcd-cpp-api-config.cmake

  but it set etcd-cpp-api_FOUND to FALSE so package "etcd-cpp-api" is
  considered to be NOT FOUND.

also includes are not set correctly as I'm getting: 'etcd/Client.hpp' file not found

**Comment by sighingnow** [comment]
Could you please try the latest master version again?

**Comment by xtrashild** [comment]
I tried it again.
I don't get the warning anymore but I still can't find the library files
fatal error: 'etcd/Client.hpp' file not found

is find_package(etcd-cpp-api) sufficient to import the library in my project?

**Comment by sighingnow** [comment]
You need

```
include_directories(${ETCD_CPP_INCLUDE_DIRS})
```

as well.

**Comment by sighingnow** [comment]
And assuming you are building target `X`, you need

```
target_link_libraries(X ${ETCD_CPP_LIBRARIES})
```

**Comment by xtrashild** [comment]
Thank you it works now.
