### ISSUE TITLE
windows vcpkg not build lib!

### ISSUE THREAD

**Issue by qugang** [etcd-cpp-apiv3/etcd-cpp-apiv3#79]
I can't generate lib files using windows vcpkg, only dll files, target_link_libraries(test PRIVATE etcd-cpp-apiv3) cannot be linked!
A warning appears when generating:
If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

     file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

**Comment by qugang** [comment]
changge CMakeLists.txt 29 lines option(BUILD_SHARED_LIBS "Build shared libraries" OFF)
copy etcd-cpp-api.lib to  vcpkg\installed\x64-windows\debug\lib
After recompiling, solve the problem!

**Comment by sighingnow** [comment]
I think we should fix the `CMakeLists.txt` for generating a implib under MSVC instead.

**Comment by qugang** [comment]
吊！
