### ISSUE TITLE
Memory leak + explanation needed

### ISSUE THREAD

**Issue by mszy** [etcd-cpp-apiv3/etcd-cpp-apiv3#83]
Hello,

Fix #50 add a potential memory leak in [file Action.cpp](https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/blob/116b49b7845f6e1a90d50d367925d3cef5930495/src/v3/Action.cpp#L42).

If string_plus_one is called with empty string, s is never deleted. Yes is a minor memory leak (one char).

Moreover, I would like to know if the calloc is really important, I tried the following code and it seems to work very well, avoiding calloc. Do you have a reason to keep it?

```cpp
// Referred from the Go implementation in etcd.
for (int32_t i = value.size() - 1; i >= 0; --i) {
      if (static_cast<unsigned char>(value[i]) < 0xff) {
	      std::string s = value.substr(0, i + 1);
	      s[i] = s[i] + 1;
	      return s;
      }
}

// see: noPrefixEnd in etcd, however c++ doesn't allows '\0' inside a string, thus we use
// the UTF-8 char U+0000 (i.e., "\xC0\x80").
return { "\xC0\x80" };
```

**Comment by sighingnow** [comment]
Thanks.

The implementation above looks good to me. Would you mind to submit a pull request for a fix?
