### ISSUE TITLE
Watch compact_revision

### ISSUE THREAD

**Issue by chitownhart** [etcd-cpp-apiv3/etcd-cpp-apiv3#90]
Can you please add the required plumbing to capture the compact_revision number from a watch response that is cancelled?

  if (reply.canceled() && reply.compact_revision() != 0) {
    error_code=grpc::StatusCode::OUT_OF_RANGE;
    error_message="required revision has been compacted";
    // index=reply.compact_revision(); // If stuffing this into existing field of V3Response / Response
    // compact_revision = reply.compact_revision(); // If stuffing this into new field of V3Response / Response
    return;
  }

**Comment by sighingnow** [comment]
Its ok to add such a field.
