### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by chitownhart** [etcd-cpp-apiv3/etcd-cpp-apiv3#94]
I couldn't find anything that discusses the thread safety of the library. The documentation talks about the async handling of requests and responses and how you can either block for the response or setup a future. But, it's not clear if multiple threads can share the same Client interface and simultaneously make calls or does every thread need a dedicated Client? If multiple threads can share a single Client interface can they all make blocking calls or does one blocking call prevent others from even being initiated?

**Comment by sighingnow** [comment]
Multiple threads can share the same client.

Multiple threads can start simultaneous requests (both blocking or nonblocking) using the same client, all requests share a asio thread pool and issue requests to etcd server simultaneously. Waiting on a response won't prevent others to initiate the request.
